### ISSUE TITLE
Add link to matrix

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#1013]
Add link to matrix in the docs/readme.

**Comment by AleCandido** [comment]
I was thinking of something like this at the top:

![Matrix](https://img.shields.io/matrix/qibo%3Amatrix.org?logo=matrix)

plus an explicit link at the bottom.

https://matrix.to/#/#qibo:matrix.org

**Comment by scarrazza** [comment]
Looks good to me.

**Comment by andrea-pasquale** [comment]
At this point shouldn't we propagate this for all public repos?

**Comment by scarrazza** [comment]
I agree, cc @AleCandido.
