### ISSUE TITLE
`DepolarizingChannel` gives wrong probabilities when used with state vectors

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#1018]
**Describe the bug**

The `DepolarizingChannel` with `lam=1` on a single qubit should give 0.5 probability for both 0 and 1 but gives 0.6 - 0.4.
The problem does not appear when using density matrices.

**To Reproduce**
```py
from qibo import Circuit, gates

nqubits = 1
qc = Circuit(nqubits)
lam = 1

qc.add(gates.DepolarizingChannel([0,], lam))
qc.add(gates.M(0))

# Execute circuit
result = qc.execute(nshots=10000)
counts = dict(result.frequencies(binary=True))
print(counts)
```

**Expected behavior**
Gives `{'0': 6316, '1': 3684}`. 

When using `qc = Circuit(nqubits, density_matrix=True)` it gives `{'0': 5035, '1': 4965}` which is more right.

**Comment by stavros11** [comment]
@renatomello @AlejandroSopena do you have any idea what could be causing this?

**Comment by renatomello** [comment]
> @renatomello @AlejandroSopena do you have any idea what could be causing this?

Since @AlejandroSopena already detected the issue and opened a PR, I put myself as a reviewer there.
