### ISSUE TITLE
Output of circuit execution

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#1020]
When executing a circuit that contains channels (noise) or collapse measurements using state vectors, qibo will automatically repeat execution multiple times (specified by the given `nshots`) and each time the channel will act non-deterministically. Then the circuit can return different things:

* if no measurements were used in the end: a list of `len(nshots)` state arrays, each one corresponding to a single execution,
* if measurements were used in the end: a `CircuitResult` object for which the samples, frequencies and probabilities are constructed from the repeated executions, however the representation and state correspond to the last execution, so they are random.

Currently `CircuitResult` attempts to accommodate all the different "modes" of execution which makes it a bit hard to use. I may be useful to collect the different "modes" of execution and possibly return different custom objects in each case. 

A proposal would be:

1. no noise, `nshots is None`, no measurements -> `QuantumState`
2. no noise, `nshots is None`, measurements -> `QuantumState` (measurements are ignored if `nshots` is not given)
3. no noise, `nshots is not None`, no measurements -> raise error because `nshots` was given but there are no measurements or noise
4. no noise, `nshots is not None`, measurements -> `Measurements` (this still has a `.state()` property to obtain the state vector since it is always available in simulation - on hardware `.state()` raises an error)
5. noise, `nshots is None`, no measurements -> raise error as we cannot simulate noise without density matrices or shots
6. noise, `nshots is None`, measurements -> raise error as we cannot simulate noise without density matrices or shots
7. noise, `nshots is not None`, no measurements -> `NoisyQuantumState` (contains a list of `len(nshots)` states obtained from each execution where noise was applied randomly)
8. noise, `nshots is not None`, measurements -> `Measurements` (can be the same object as 4 but it does not provide `.state()` - similar to when executing on hardware)

For `density_matrix=True` we can follow the same pattern, except that for 5, 6 we can still return a `QuantumState` containing the density matrix. Or we could even have separate `Statevector` and `DensityMatrix` objects to be more explicit.

This is a quick sketch, any suggestions are welcome.

**Comment by BrunoLiegiBastonLiegi** [comment]
After a discussion with @stavros11 we decided that, as `nshots` is usually tightly connected to whether we perform a measurement or not, to set a default value `nshots=1000`. This simplify a bit the cases we have:

1. no noise, no measurements --> `QuantumState`
2. no noise, measurements --> `QuantumState`, `MeasurementOutcomes`
3. noise, no measurements --> raise error if `density_matrix=False`
4. noise, measurements --> `MeasurementOutcomes`

if `density_matrix=True` case 3 can be handled:

5. noise, no measurements --> `QuantumState` (mixed and given by the statistics of the repeated executions, we might also store  all the final state obtained)

At the moment I am not sure whether it is better to add a third object `CircuitOutput` that contains both the `QuantumState` and the `MeasurementOutcomes` , what would you suggest @stavros11.

**Comment by stavros11** [comment]
Thank you for the summary @BrunoLiegiBastonLiegi. I agree with these categories, just mentioning two additional points:
* Hardware execution also falls to point 4. No action needed for that from the qibo side but we need to consider when updating the `QibolabBackend`.
* Point 4 is slightly different when `density_matrix=True` because the full density matrix is available even in the case of noise, so we can return `[QuantumState, MeasurementOutcomes]`.

> At the moment I am not sure whether it is better to add a third object `CircuitOutput` that contains both the `QuantumState` and the `MeasurementOutcomes` , what would you suggest @stavros11.

I think there is some value in having a custom object over the tuple `(QuantumState, MeasurementOutcomes)`, in order to keep the same interface. Eg.
```py
result1 = circuit_without_measurements()
# result1 is `QuantumState`
print(result1.state())

result2 = circuit_with_measurements(nshots=1000)
# result2 is `CircuitOutput`
print(result2.state()) # basically queries the `QuantumState` inside the `CircuitOutput`
```
If `result2` was something else (eg. a `tuple`) we would create an assymetry.

Instead of `CircuitOutput` we could also keep the `CircuitResult` name for this case, to minimize the interface changes with the current version. This way for point 2 (which is probably the most commonly used mode) there will be no change from the user side (even if we change the internals). Let me know if you agree.
