### ISSUE TITLE
Implementation of a Clifford simulator in the `quantum_info` module

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1051]
Following an in-person discussion with @scarrazza, I will list here two enhancements that we need to implement as soon as possible:

- Clifford simulator following [Aaronson and Gottesman (2004)](https://arxiv.org/abs/quant-ph/0406196#)
- Implementation of conversion of Clifford objects from tableaus to circuits in the normal form following Section 2.2. of [Bravyi and Maslov (2020)](https://arxiv.org/abs/2003.09412). The normal form is already implemented in `quantum_info.random_clifford`. We are missing the canonical form from Aaronson & Gottesman + conversion between the two representations.

**Comment by BrunoLiegiBastonLiegi** [comment]
Also this [https://quantum-journal.org/papers/q-2021-07-06-497/](url) was suggested to me by @AlejandroSopena and might be relevant.

**Comment by AleCandido** [comment]
> Also this [quantum-journal.org/papers/q-2021-07-06-497](https://quantum-journal.org/papers/q-2021-07-06-497/) was suggested to me by @AlejandroSopena and might be relevant.

I just found this again while inspecting `https://github.com/quantumlib`.

I'd say that integrating [Stim](https://github.com/quantumlib/stim) would be more effective than rewriting from scratch.

---

Furthermore, I found this other simulator you might already be aware of:

> Implementation: https://github.com/asciineuron/bgls
Based-on paper: https://arxiv.org/abs/2112.08499

I wonder if you know whether there is any real advantage in having it, and if it's worth a separate issue.
