### ISSUE TITLE
Tests failing for `qibojit-cupy`

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1065]
By installing both `qibo` and `qibojit` from `master` and running `pytest -x tests/`, we get

```python3

FAILED tests/test_callbacks.py::test_entropy_in_distributed_circuit[qibojit-cupy-accelerators4-gateconf0-target_entropy0] - ModuleNotFoundError: No module named 'qibo.states'

```

**Comment by scarrazza** [comment]
@stavros11 @BrunoLiegiBastonLiegi could you please have a look?

**Comment by BrunoLiegiBastonLiegi** [comment]
Have you installed qibo from master with poetry? Because I think that if you install qibojit with poetry, it will downgrade qibo to 0.2.0 version, thus, the tests will fail.

**Comment by stavros11** [comment]
> ```python
> FAILED tests/test_callbacks.py::test_entropy_in_distributed_circuit[qibojit-cupy-accelerators4-gateconf0-target_entropy0] - ModuleNotFoundError: No module named 'qibo.states'
> ```

This is probably related to https://github.com/qiboteam/qibojit/blob/0519c0e2273563d6439583fdca8d3010acb5dd19/src/qibojit/backends/gpu.py#L324. Qibojit needs to be updated for the new result objects. I also get several other failures for cupy though.

**Comment by scarrazza** [comment]
@BrunoLiegiBastonLiegi could you please have a look with @stavros11?

**Comment by BrunoLiegiBastonLiegi** [comment]
Yes, I think @stavros11 is right, I need to update the qibojit backend to accomodate for the new outcomes object, as I did for qibolab. I forgot about that, sorry.
