### ISSUE TITLE
Latest `cupy` release introduced matrix exponentiation

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1068]
Latest `cupy` [release](https://github.com/cupy/cupy/releases/tag/v13.0.0b1) finally introduced a native version of `scipy.linalg.expm`.
So we could finally implement this operation in a backend-agnostic way instead of defaulting to `numpy` and then using `cast`

**Comment by andrea-pasquale** [comment]
I can have a look into this. It is needed to speed up #1047.

**Comment by andrea-pasquale** [comment]
I give it a try but we cannot test it since the `setup.py` of cupy is currently broken https://github.com/cupy/cupy/issues/8185.
Depending on when this issue is fixed we might postpone this to the next release.

**Comment by leofang** [comment]
Wearing my CuPy hat here... Nothing is broken, not sure what you meant @andrea-pasquale? You can always install CuPy wheels `cupy-cuda11x` or `cupy-cuda12x`, without spending any time on compilation. Even if building CuPy from source, it should still work. The issue that you linked to is just an innocent, inaccurate run-time info reporting.

**Comment by andrea-pasquale** [comment]
A quick update: in version `13.0.0` `expm` is only available for real matrices https://github.com/cupy/cupy/issues/8205.
The fix was been already merged to main so by building cupy from source we should be able to include it, I suggest waiting for next release before propagating this change to qibo(jit).

**Comment by andrea-pasquale** [comment]
@scarrazza maybe it is better to avoid to include this issue in a milestone until the next cupy version gets released.

**Comment by scarrazza** [comment]
I agree, please go ahead and change it.
