### ISSUE TITLE
Error in pytest for qibo.set_backend("tensorflow")

### ISSUE THREAD

**Issue by jykhoo1987** [qiboteam/qibo#1082]
I am trying to raise a pull request to add some features to the qcnn model class. However I am encountering an error in pytest specifically for build (windows-latest, 3.11) / build as shown below:

=========================== short test summary info ===========================
[288](https://github.com/qiboteam/qibo/actions/runs/6790351686/job/18459561498#step:11:289)
FAILED tests/test_models_qcnn.py::test_qcnn_training - ModuleNotFoundError: No module named 'tensorflow'
[289](https://github.com/qiboteam/qibo/actions/runs/6790351686/job/18459561498#step:11:290)
===== 1 failed, 4582 passed, 43 skipped, 30 warnings in 215.88s (0:03:35) =====
[290](https://github.com/qiboteam/qibo/actions/runs/6790351686/job/18459561498#step:11:291)
Error: Process completed with exit code 1.

This error is returned when qibo.set_backend("tensorflow") is run, but as per the tutorial (https://qibo.science/qibo/stable/getting-started/installation.html#installing-tensorflow), this should work.

**Comment by scarrazza** [comment]
Just a quick check: did you install tensorflow in the same environment where are you running pytest?

**Comment by jykhoo1987** [comment]
No I did not. Do you mean that in the test script, I will need to first install tensorflow?

**Comment by scarrazza** [comment]
Yes, you have to install all test dependencies.

**Comment by jykhoo1987** [comment]
Ok thanks! Will keep that in mind for future pytests, for now I think it is not necessary to include it since we only use it through qibo.optimizer.
