### ISSUE TITLE
Transpiler `is_satisfied` attribute

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#1086]
Requests from qiboteam/qibolab#643:

- [ ] Currently `StarConnectivity` and `Passes` have the `is_satisfied` attribute, while the other transpilers do not. We need to decide if we will keep it and make sure it is consistent. It may be useful to have a quick way to check if a circuit already satisfies a transpiler (ie. only has native gates or respects connectivity) so that we can skip the transpilation step for this circuit.
- [ ] `Placer` and `Router` demo tutorial for documentation.

**Comment by Simone-Bordoni** [comment]
For now we have the fuctions "assert_connectivity" and "assert decomposition". If you want i can create an "is satisfied" method for router, unroller and pipeline that calls these function based on the connectivity/native gates. There is now a tutorial in "advanced_examples", do you want to add it somewhere specific?

**Comment by stavros11** [comment]
Thanks @Simone-Bordoni. At this point, I think we could drop `is_satisfied` completely from the transpilers. It was mostly used for qibolab but we can do this check internally in the `QibolabBackend` if needed.

The tutorial was requested by @jykhoo1987 so I would ask him if what we now have in https://github.com/qiboteam/qibo/blob/master/doc/source/code-examples/advancedexamples.rst#how-to-modify-the-transpiler (which will be rendered in the docs in the next release) is sufficient or no. I believe it is fine putting it under advanced examples.

**Comment by Simone-Bordoni** [comment]
is satisfied has been dropped, i think we can close this issue

**Comment by jykhoo1987** [comment]
@stavros11 thank you very much, the improved tutorial you linked is much more comprehensive than before. At first glance it looks to be sufficient. I will try it out in detail at some point and get back to you if I find something missing or unclear.

@Simone-Bordoni @stavros11 thanks for looking into this.
