### ISSUE TITLE
List available backends

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibo#1096]
It would be nice if Qibo were able to check if a backend is available, and have a function to survey all the registered backends, and list those available.

Possibly, it could be implemented even trying to load it, and catching the failure. But if each backend had a property `available` it would be even better.
(since the backend might know about the required conditions for availability, and we'd avoid catching a generic error)

**Comment by renatomello** [comment]
This is basically what's already implemented [here](https://github.com/qiboteam/qibo/blob/42867eb6fdd8af82a933a67fd29f552a2b6c29b8/src/qibo/backends/__init__.py#L61), no?

**Comment by alecandido** [comment]
My idea would be something like:

```py
def available_backends():
   ...

available_backends()
#
# {
#    "numpy": True,
#    "numba": True,
#    "cupy": False,
#    ...
# }
```

**Comment by renatomello** [comment]
@alecandido I understand. What I was saying is that one could basically repackage that part of the code as a standalone function and it would already do the job (even if not in the most elegant way)

**Comment by alecandido** [comment]
Yes, that's fine, we could definitely use it.

We're missing something like what is partially in `GlobalBackend`:
https://github.com/qiboteam/qibo/blob/42867eb6fdd8af82a933a67fd29f552a2b6c29b8/src/qibo/backends/__init__.py#L54-L59
i.e. a comprehensive list.

Moreover, since the mechanism of platforms is more or less uniform (though not fully, with built-in ones being the exception), most likely it should be something like:
```py
{
    "core": {
        "numpy": True,
        "tensorflow": True,
    },
    "qibojit": False,
    "qibolab": {
        "tii1q_b1": True,
        "iqm5q": True,
        ...,
    },
    "qibotn": { ... },
}
```
and register some tiny classes that include the platform discovery mechanism for each of them (instead of implementing all of them in Qibo - it is already like this in Qibolab, but it's just a function).

The class could be just:
```py
class MetaBackend:
    def load(platform: str) -> Backend:
        ...

   def list() -> dict[str, bool]:
       """Having dict mapping to bool could be equivalent to have a list
          for some backends, e.g. Qibolab, but used by others to check dependencies
          and hardware availability, e.g. Qibojit.
      """
      ...
```
(there is some confusion among the names "backend", "platform", so I chose a different one to disambiguate - but names are all up for discussion)

**Comment by BrunoLiegiBastonLiegi** [comment]
Ok, so, just to make sure that I have understood. The `MetaBackend` should take over the role of the current `construct_backend` function?
Namely, giving it will be capable of constructing the selected backend, but in addition also able to list the available backends. However, the mechanism for listing the available backends is still going to go through a bunch of `try/except` statements, right?

**Comment by alecandido** [comment]
`MetaBackend` was a random name and random structure. But the goal was to make it hierarchical.

So, if you want to have a single `set_backend()` that accepts a string, you still need to register the various `MetaBackend` in `qibo`, with a `construct_backend()` function.
The idea is to make this registration simple, and agnostic of the internal structure of the other packages, so to register *one* `MetaBackend` per external package (one for `qibojit`, one for `qibolab`, one for `qibotn`, one for `qibo-cloud`, and even just a single one for the built-in).

**Comment by alecandido** [comment]
> However, the mechanism for listing the available backends is still going to go through a bunch of `try/except` statements, right?

In my mind, this should have been up to the individual backends.
E.g. if you have in mind `qibojit`, for sure: you could either `try/except` for dependencies, or you could check if a GPU is available and similar.
However, for Qibolab there is no `try/except`, you should just list the platforms available reading them from the proper folder.

**Comment by BrunoLiegiBastonLiegi** [comment]
@alecandido can you check whether [this](https://github.com/qiboteam/qibojit/pull/172) qibojit `MetaBackend` object goes in the direction you suggested?

**Comment by BrunoLiegiBastonLiegi** [comment]
I created an analogous `MetaBackend` class in `qibo` that is going to use all the different `MetaBackend`  objects defined in the other repos. Qibojit's one is ready, I guess I will work on the `qibolab`'s and `qibo-cloud-backends`' one (for this last one I was also thinking about changing the name of the repo to `qibocloud`).

**Comment by alecandido** [comment]
Maybe the `MetaMetaBackend` should not be named `MetaBackend` on its own, and they could be just separate functions, you do not need even a class to collect them.

But it's fine to have something, and to make it work. Then we can refine how it looks like.
