### ISSUE TITLE
`Segmentation Fault` on `VQE` tests

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1122]
Link to the error in CI

https://github.com/qiboteam/qibo/actions/runs/7096791067/job/19315844018?pr=1116

https://github.com/qiboteam/qibo/actions/runs/7097067492/job/19316577340?pr=1056

https://github.com/qiboteam/qibo/actions/runs/7098179504/job/19319611749

EDIT: This seems to only happen on MacOS

**Comment by renatomello** [comment]
@stavros11 @AleCandido

**Comment by scarrazza** [comment]
I confirm this is not happening outside github's CI.
