### ISSUE TITLE
Wires names

### ISSUE THREAD

**Issue by Simone-Bordoni** [qiboteam/qibo#1130]
Add the possibility to define wires names in a circuit. They will be printed using circuit.draw() instead of the standard "q0", "q1", "q2"... This is useful when transpiling circuits on a subset of qubits to avoid deceptive printing. 

example:
```python
circuit = Circuit(3, wires_names = ['ancilla', 'hi', 'q2'])
circuit.draw()
```

ancilla: -------
hi       : -------
q2      : --------

another possibility can be passing a dictionary used to rename only a subset of wires like:
```python
circuit = Circuit(3, wires_names = {'q0': 'ancilla', 'q2': 'hi'})
circuit.draw()
```

ancilla: -------
q1       : -------
hi        : --------

It is important that wires names is not just an argument of the draw function as the transpiled circuit should have the same name of the wires as the physical qubits.
for example:

```python
topology = nx.Graph()
topology.add_nodes_from([0, 1, 2, 3, 4])
topology.add_edges_from([(0, 2), (1, 2), (2, 3), (2, 4)])
transpiler = Passes(connectivity=topology, qubits=[2,4])
circuit = Circuit(2)
transpiled_circuit, qubit_map = transpiler(circuit)
transpiled_circuit.draw()
```
q2       : -------
q4       : -------

**Comment by renatomello** [comment]
I think both ways suggested are good and should be implemented. It gives flexibility.
