### ISSUE TITLE
Qubit specific extension to qibo noise model

### ISSUE THREAD

**Issue by jykhoo1987** [qiboteam/qibo#1158]
The current composite NoiseModel is limited to the same 'depolarizing error' for one- and two-qubit gates across all qubits. It would be good to have the ability to input different values of for different qubits, which is likely the case as well in hardware. The ‘excited population’ should also have this flexibility as well.

@rahula06 @shangtai

**Comment by renatomello** [comment]
IIRC that's already allowed, because the `qubits` variable from the `NoiseModel.add` method allows for tuples. See https://qibo.science/qibo/stable/api-reference/qibo.html#noise.
