### ISSUE TITLE
Error mitigation tests failing on GPU

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibo#1184]
Some tests regarding `error_mitigation` are failing on GPU backends. Here is a screenshot:
![image](https://github.com/qiboteam/qibo/assets/49183315/699f3302-622a-406f-aeea-b42058d7817b)
The fix should be quite easy to implement, we just need to be careful when dealing with cupy arrays.

**Comment by AlejandroSopena** [comment]
The tests are passing locally for me. What version of CUDA, cupy, and cuquantum are you using?

**Comment by andrea-pasquale** [comment]
I'm using `cuda12.2`, `cupy12.2` and `cuquantum23.10`.
In order to test on GPU properly you need to be sure to have everything installed correctly. 
You can even use the `-v` option when running `pytest` to see which configuration you are using for each test.

**Comment by AlejandroSopena** [comment]
Thanks. Yes, I have checked the tests pass with cupy and cuquantum. I suppose the issue is that I'm still using `cuda11.6` and `cuquantum22.11` . I will update them to reproduce the error and fix it.

**Comment by andrea-pasquale** [comment]
Thanks @AlejandroSopena. Btw, I assigned you just because you were the last one to work on this. I can take over if you find any issues.

**Comment by andrea-pasquale** [comment]
Thanks for sharing tests. I will check which versions of `qibo` and `qibojit` I am using. I think this could be the only difference. If  I remember correctly was using `main` for both.

**Comment by AlejandroSopena** [comment]
I am also using `main` for both. Another difference could be the `numpy` version.  I am using `numpy1.26.3`
