### ISSUE TITLE
Add tensor network support for as a qibo backend for simulation

### ISSUE THREAD

**Issue by liweintu** [qiboteam/qibo#1221]
**Is your feature request related to a problem? Please describe.**
This request is to enable tensor network support for accelerated and scalable simulation in qibo.

**Describe the solution you'd like**
We can add a new backend in qibo for users to specify the tensor network backend for simulation.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by renatomello** [comment]
@liweintu https://github.com/qiboteam/qibotn
