### ISSUE TITLE
Replace `hyperopt`

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibo#1232]
After https://github.com/qiboteam/qibo/issues/1231#issuecomment-1968367678 I reviewed the state of `hyperopt`, and it's definitely unmaintained. The authors are not replying to the issues, and the contributions to the code are practically stuck.

If we care about the features supported by `hyperopt`, it should be replaced soon.

**Comment by alecandido** [comment]
@MatteoRobbiati I'm not sure how this relates to `qiboml`. It is only used in DBI.

**Comment by andrea-pasquale** [comment]
There were already some discussions about including `hyperopt` as a dependency or not...
I think it should be easy to eventually move to [`optuna`](https://github.com/optuna/optuna)  which seems to be more maintained.

**Comment by alecandido** [comment]
Indeed, I was having a look as well, and `optuna` seems much more reliable!

**Comment by renatomello** [comment]
Since this is related to DBI: some the DBI tests are *very* slow right now. Could this be improved as well?
