### ISSUE TITLE
The future of conda packages

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#1246]
The latest release (0.2.5) includes `openqasm3` which seems not available in conda-forge and therefore we cannot generate conda packages for qibo:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=887722&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3

We have to decide how to deal with this, e.g. limiting to deps with conda-forge builts, finding replacements or simply do not supporting conda anymore. Any thoughts?

**Comment by alecandido** [comment]
To be completely fair: I was unaware we still had a conda package...

Is packaging openqasm3 ourselves an option?

**Comment by BrunoLiegiBastonLiegi** [comment]
I was able to build the conda package using [grayskull](https://github.com/conda/grayskull) and `conda-build` in case we still want to have it.

**Comment by BrunoLiegiBastonLiegi** [comment]
I am trying to register to [Anaconda.org](Anaconda.org), however there apparently is a bug ([https://github.com/ContinuumIO/anaconda-issues/issues/11293](https://github.com/ContinuumIO/anaconda-issues/issues/11293)) which prevents me from registering there.

**Comment by scarrazza** [comment]
Please use conda-forge instead of anaconda (no need for accounts, just a pull request).

**Comment by alecandido** [comment]
https://conda-forge.org/docs/maintainer/adding_pkgs/

**Comment by BrunoLiegiBastonLiegi** [comment]
Yep thanks I forked and added the recipe as they suggest in the docs. However, I am having troubles testing locally, namely when I run the `build-locally.py` script they provide I get an error:
```
fatal: detected dubious ownership in repository at '/home/conda/staged-recipes'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/conda/staged-recipes
```
I tried to make the directory 'safe' in several ways, but I cannot get past this.

**Comment by alecandido** [comment]
Why is it in the `conda` user?

**Comment by alecandido** [comment]
I take it back: most likely you're trying to use Git with your user, but you're not the owner

> Well, firstly the reason for the error message is because git will check if the current user is the owner of the git repository folder, and will produce the above error if the current user is not the owner.

https://medium.com/@thecodinganalyst/git-detect-dubious-ownership-in-repository-e7f33037a8f

**Comment by scarrazza** [comment]
You have to fork the conda-forge feedstock repository with your account and open a PR. Then, the conda forge maintainers will review the recipe and decide to merge (usually takes 1 week, if everything is good).

**Comment by BrunoLiegiBastonLiegi** [comment]
I opened the PR but, rightfully, pylint signaled me that there's already a conda `openqasm3` package [https://anaconda.org/conda-forge/openqasm3](https://anaconda.org/conda-forge/openqasm3).

**Comment by alecandido** [comment]
Ok, then the error is not that there is no `openqasm3` on conda-forge, but that the feedstock of Qibo should be updated to add it as a dependency.

**Comment by scarrazza** [comment]
Oh, that is great, let me give a try.

**Comment by scarrazza** [comment]
Thanks @BrunoLiegiBastonLiegi for all checks. I am closing this now, ref. https://github.com/conda-forge/qibo-feedstock/pull/18
