### ISSUE TITLE
Tensorflow dependency

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#1251]
I noticed that doing
```py
pip install qibo
```
in a clean environment installs tensorflow, even though this used to be an optional dependency. Is this expected behavior, or is there something wrong?

**Comment by scarrazza** [comment]
Obviously, this should not happen at all. @alecandido could you please double check the toml configuration please?

**Comment by alecandido** [comment]
It happened to me as well, but I was waiting for developments in https://github.com/qiboteam/qibo-core/ and https://github.com/qibogang/qiboml/ before facing the issue.

Let me try a hotfix.
