### ISSUE TITLE
`numpy` 2.0.0 release

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1256]
https://github.com/numpy/numpy/releases/tag/v2.0.0b1

It might be interesting to look into it to see if any speed-up can be obtained by supporting `numpy` 2.0.0.
(@BrunoLiegiBastonLiegi maybe in the Clifford implementation?)

**Comment by BrunoLiegiBastonLiegi** [comment]
I quickly looked into the `performance improvements` section, but I don't think there's anything that we use in the `CliffordBackend`. Worth a try though.
