### ISSUE TITLE
Coverage decrease

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#1263]
It looks like we are missing some lines related to clifford:
- https://app.codecov.io/gh/qiboteam/qibo/blob/master/src%2Fqibo%2Fbackends%2Fclifford.py
- https://app.codecov.io/gh/qiboteam/qibo/blob/master/src%2Fqibo%2Fgates%2Fspecial.py

@renatomello @BrunoLiegiBastonLiegi could you please have a look?

**Comment by renatomello** [comment]
There's already a fix for it in #1202, which is close to being merged.

**Comment by renatomello** [comment]
There's already a fix for it in #1202, which is close to being merged.
