### ISSUE TITLE
Do we still need `dill`?

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1267]
@scarrazza @alecandido I spoke with @stavros11 and he said that `dill` was a solution for a problem that doesn't apply anymore. It is not used anywhere besides `pyproject.toml` and `test_dill.py`

**Comment by stavros11** [comment]
The problem I was referring to was the jupyter notebook runtime submission to slurm nodes, which I believe is not maintained anymore. I do not recall any other application of `dill` from our side.

**Comment by alecandido** [comment]
The submission has been replaced by the serialization and the new [`qibo-client`](https://github.com/qiboteam/qibo-client) based on it.

I'd say that `dill` is not required any longer, though consider that serialization is currently limited, waiting for a general gate refactor (I will try to start it after `qibo-core` initial adoption), and I'm not sure if Hamiltonians and symbols are actually supported (but most likely they are not even used).

**Comment by scarrazza** [comment]
My recollection is similar to @stavros11, at this stage, we don't need dill anymore including serialization as mentioned by @alecandido.

**Comment by renatomello** [comment]
> and I'm not sure if Hamiltonians and symbols are actually supported (but most likely they are not even used).

What do you mean by not even used?

**Comment by alecandido** [comment]
For remote execution
