### ISSUE TITLE
qibo.set_backend("pytorch") is not available

### ISSUE THREAD

**Issue by bpcarlos** [qiboteam/qibo#1268]
**Describe the bug**
Error when trying to set PyTorch as a qibo backend.

**To Reproduce**
```
!pip install qibo
!pip install qibo torch

import qibo
qibo.set_backend("pytorch")
```
`ValueError: Backend pytorch is not available.`

**Additional context**
We are trying to use pytorch as backend in a similar fashion I used TensorFlow in the past with the help of @stavros11 (https://github.com/QTI-TH/style-qgan/blob/v1.0.0/tutorial_notebook/style-qGAN-Tutorial.ipynb)

I am unsure if the error is to be expected, as I see you are currently working on the backend, and probably it has been recently implemented (?)
We are trying to use it because we saw it is available in the Qibo documentation, and the backend perfectly fits one of the projects I am currently working on.

**Comment by andrea-pasquale** [comment]
Hi @bpcarlos, `pytorch` is currently available only when installing qibo [from source](https://qibo.science/qibo/stable/getting-started/installation.html#installing-from-source).
It will be available through `pip install qibo` after we release qibo `0.2.7`.
It will not be necessary to install `torch`afterwards either,  it should be included as a dependency of qibo.

**Comment by bpcarlos** [comment]
Thanks for the answer, @andrea-pasquale! Another quick question: do you happen to know if the current pytorch backend installed from qibo source admits the same options as the tensorflow backend? Eg. Automatic differentiation, etc

**Comment by andrea-pasquale** [comment]
I don't think so yet https://github.com/qiboteam/qibo/issues/1266 (cc @renatomello @Simone-Bordoni)

**Comment by renatomello** [comment]
> Thanks for the answer, @andrea-pasquale! Another quick question: do you happen to know if the current pytorch backend installed from qibo source admits the same options as the tensorflow backend? Eg. Automatic differentiation, etc

The `torch` PR was too big already, so we decide to split it and do the autodifferentiation integration in a follow-up PR in the next weeks by @Simone-Bordoni

**Comment by bpcarlos** [comment]
Ok, thanks @renatomello.

**Comment by Simone-Bordoni** [comment]
@bpcarlos if you want to use the new pytorch backend you can do it but for now it has not any integrated automatic differentiation functions. A first feedback on this backend would be really useful especially to check if the gradients are correctly passing. We aim at integrating the automatic differentiation like for the tensorflow backend in the next weeks.
