### ISSUE TITLE
Change to Circuit.measurements broke to_qasm()

### ISSUE THREAD

**Issue by bdg221** [qiboteam/qibo#1283]
**Describe the bug**
This bug was discovered from the Mitiq integration. Currently, things are working properly with version 0.2.4, however in both 0.2.5 and 0.2.6 the to_qasm() method in qibo>models>circuit.py builds the QASM file incorrectly when there are multiple classical measurement registers. Checking the code, the to_qasm() method did not change, but instead the measurements part of the circuit implementation changed.

Here is a quick reproduction of the issue:
```
(mitiqqibo) zzzzz@zzzzz mitiq_bg % pip list | grep qibo
qibo                            0.2.6
(mitiqqibo) zzzzz@zzzzz mitiq_bg % python
Python 3.11.8 (main, Feb 26 2024, 15:36:12) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from qibo.models.circuit import Circuit as QiboCircuit
>>> qasm = 'OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[2];\ncreg m0[2];\ny q[0];\nx q[1];\nmeasure q[0] -> m0[0];\nmeasure q[1] -> m0[1];'
>>> qibo_cirq = QiboCircuit.from_qasm(qasm)
>>> qasm_final = qibo_cirq.to_qasm()
>>> print(qasm + "\n\n" + qasm_final)
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg m0[2];
y q[0];
x q[1];
measure q[0] -> m0[0];
measure q[1] -> m0[1];

// Generated by QIBO 0.2.6
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg m0[1];
creg m0[1];
y q[0];
x q[1];
measure q[0] -> m0[0];
measure q[1] -> m0[0];
```

Here are screenshots showing the difference in the measurements property of the Qibo circuit:
0.2.4
![image](https://github.com/qiboteam/qibo/assets/62308289/2af3d755-cb49-4aef-a717-519720af83b9)

0.2.6
![image](https://github.com/qiboteam/qibo/assets/62308289/86ea01d0-f9e9-451f-888c-f91704251b42)

**To Reproduce**
Run the following test code:
```
from qibo.models.circuit import Circuit as QiboCircuit

qasm = 'OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[2];\ncreg m0[2];\ny q[0];\nx q[1];\nmeasure q[0] -> m0[0];\nmeasure q[1] -> m0[1];'

qibo_cirq = QiboCircuit.from_qasm(qasm)
qasm_final = qibo_cirq.to_qasm()

print(qasm)
print(qasm_final)```



**Expected behavior**
Calling to_qasm() should generate a valid QASM file.

**Comment by BrunoLiegiBastonLiegi** [comment]
Thanks for reporting this! I implemented a quick fix for this in #1284, let's see whether the CI is passing.
