### ISSUE TITLE
Unroller duplicates gates when measuring in specific basis

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibo#1318]
When applying a measurement there is the possibility to specify in which basis we want to perform the measurement using the [basis](https://github.com/qiboteam/qibo/blob/24acee037138d995b4ea5acfb56d9f32831415ae/src/qibo/models/circuit.py#L660-L662) argument.

However, when such circuit is transpiled the "rotation gate" appears twice and only once it is correctly transpiled.
Here is an example:

```py
from qibo import Circuit, gates
from qibo.transpiler.unroller import NativeGates, Unroller

unroller = Unroller(native_gates=NativeGates.default())

nqubits = 2
circuit = Circuit(nqubits)
circuit.add(gates.M(i, basis=gates.X) for i in range(nqubits))

print(circuit.draw())
# which gives
# q0: ─H─M─
# q1: ─H─M─
transpiled_circuit = unroller(circuit)
print(transpiled_circuit.draw())
# which gives
# q0: ─Z─GPI2─H─M─
# q1: ─Z─GPI2─H─M─
```
In the transpiled circuit `H` appears twice, once it is compiled into natives as `Z` and `GPI2` while the second times appears as `H` which will trigger an error since it is not a native gate.
@Edoardo-Pedicillo I believe that this is not related to PRs that you recently open since I am using `master`.

**Comment by Edoardo-Pedicillo** [comment]
> @Edoardo-Pedicillo I believe that this is not related to PRs that you recently open since I am using `master`.

I confirm it is not related
