### ISSUE TITLE
test_process_fidelity_and_infidelity() test failed

### ISSUE THREAD

**Issue by csookim** [qiboteam/qibo#1405]
When I ran pytest on macos 3.10, the test_process_fidelity_and_infidelity() test failed. It passed when I ran it again.

[reference](https://github.com/qiboteam/qibo/actions/runs/10138282762/job/28029732991#step:9:266)

![Screenshot 2024-07-29 at 14 00 00](https://github.com/user-attachments/assets/811d3e7e-fc76-41f8-ac37-7b4189d12917)

**Comment by renatomello** [comment]
@csookim even though this doesn't seem to be reproducible, I created #1407 with a small change that should help
