### ISSUE TITLE
Complex numbers in samples and frequencies

### ISSUE THREAD

**Issue by marekgluza** [qiboteam/qibo#1412]
We have been submitting jobs to qw5q_platinum using the latest qibolab release 0.1.8 (`module load qibo`)

```python
import qibo
c = qibo.Circuit(5)
c.add(qibo.gates.GPI2(0,0))
c.add(qibo.gates.M(0,1,2,3,4))
result = c(nshots=100)
print(result.samples())
```

when we switch to frequencies it also fails because the results variables are complex

**Comment by scarrazza** [comment]
The bug was introduced in https://github.com/qiboteam/qibo/commit/6cc64b3bba26f325e0d8d19558bb11adce8f16fe. Btw, we should include some test to avoid this issue in the future.

**Comment by renatomello** [comment]
I could not reproduce it, after installing `qibo` from `master` and trying every backend available.

**Comment by scarrazza** [comment]
@renatomello, you have to try this code with the qibolab backend. In this case we are using `qw5q_platinum`.
