### ISSUE TITLE
Variable not defined in `mpldrawer`

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1437]
@MatteoRobbiati @sergiomtzlosa 

PR #1370 introduced the new `ui` module to `master`. There is a helper function in the module that is raising a `lint` error due to an undefined variable. The specific line is [this one](https://github.com/qiboteam/qibo/blob/4f2314ab2cc311894dbb05c862c5c8cc63b75ec0/src/qibo/ui/mpldrawer.py#L604). This is preventing tests from passing, e.g. https://github.com/qiboteam/qibo/actions/runs/10715691273/job/29711648870

**Comment by MatteoRobbiati** [comment]
Thanks for spotting this! @sergiomtzlosa, should we pass the circuit as an argument so that we keep that line or do you think we can do that in a different way?

**Comment by sergiomtzlosa** [comment]
sorry! I did not spot this, I push a fix for this, I just submit a commit to fix this bug

**Comment by alecandido** [comment]
Yeah, unfortunately we didn't notice because the CI was not running, since the PR came from a fork.

However, this may happen for new PRs, even from forks. If that's not the case, please repeat to me or @scarrazza

**Comment by MatteoRobbiati** [comment]
> sorry @renatomello and @MatteoRobbiati ! I did not spot this, I just submit a commit to fix this bug

No problem. Are you going to open a PR for this?

**Comment by sergiomtzlosa** [comment]
yes! here is the pull request https://github.com/qiboteam/qibo/pull/1438
