### ISSUE TITLE
Doc tests failing because of `%matplotlib inline`

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1443]
@MatteoRobbiati @sergiomtzlosa documentation tests are failing because of the command `%matplotlib inline` introduced in three examples., e.g. https://github.com/qiboteam/qibo/actions/runs/10791577495/job/29931043412?pr=1441#step:10:215

**Comment by MatteoRobbiati** [comment]
I fixed it in #1338 and a duplicate fix is ongoing in #1438. 
Later in the meeting I will suggest to review and merge my PR #1338 to fix the couple of problems you noticed and to use #1438 to complete the coverage.
