### ISSUE TITLE
Deprecate conda packages?

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#1460]
We are producing Conda packages for qibo, qibolab, qibocal, and qibojit. However, we do not test or use them in production. I feel that we should discontinue these packages and keep pip as the default/tested package manager.

Any thoughts?

**Comment by alecandido** [comment]
I would agree to discontinue them. I'd avoid increasing the maintenance burden, as much as possible.

In case there will be a strong need, we could reassess later on.
