### ISSUE TITLE
QAOA and VQE variational models not exposing the circuit

### ISSUE THREAD

**Issue by NithyasriVS** [qiboteam/qibo#1498]
I'm trying to build a QAOA feature for qibotn and need the circuit with the alternating layers of the cost and mixer hamiltonians but the circuit is not being exposed for example, I'm unable to get the circuit with a .circuit after minimize() with the final parameters. I face similar experience with VQE.

Is there any way I could extract the circuit rather than having to build the alternating layers myself? Thanks, any insights and help are appreciated

**Comment by renatomello** [comment]
Using the example inside the `VQE` class' docstring, it seems that it is possible to get the `circuit` attribute after running `VQE.minimize`:

```python
In [1]: import numpy as np
   ...: from qibo import Circuit, gates
   ...: from qibo.models import VQE
   ...: from qibo.hamiltonians import XXZ
   ...: 
   ...: # create circuit ansatz for two qubits
   ...: circuit = Circuit(2)
   ...: circuit.add(gates.RY(0, theta=0))
   ...: # create XXZ Hamiltonian for two qubits
   ...: hamiltonian = XXZ(2)
   ...: # create VQE model for the circuit and Hamiltonian
   ...: vqe = VQE(circuit, hamiltonian)
   ...: # optimize using random initial variational parameters
   ...: initial_parameters = np.random.uniform(0, 2, 1)
   ...: vqe.minimize(initial_parameters)
   ...: 
   ...: vqe.circuit.draw()
[Qibo 0.2.13|INFO|2024-10-22 09:05:43]: Using qibojit (cupy) backend on /GPU:0
q0: ─RY─
q1: ────
```

**Comment by NithyasriVS** [comment]
Thank you, @renatomello! May I ask if there's any specific reason why this is not possible with QAOA. Thanks again for the quick reply!

**Comment by renatomello** [comment]
> Thank you, @renatomello! May I ask if there's any specific reason why this is not possible with QAOA. Thanks again for the quick reply!

I am not an expert on the Hamiltonian part of the `qibo` code but after a quick look at it, it seems that the time evolution via `QAOA` is done mostly via direct exponentiation of Hamiltonian(s) + matrix multiplication with an initial state. It only performs circuit execution if the `solver` is the `TrotterizedExponential` solver, which in turn only happens if one chooses `solver="exp"` *and* the Hamiltonian is from the `SymbolicHamiltonian` class. I don't think the circuit(s) would be exposed in that case either, but my point is that unless you're in that specific case, the circuit appears to not even be defined to begin with.

**Comment by NithyasriVS** [comment]
Sure, thanks for sharing your insights. I asked the question because I came across these lines of code in QAOA class and was wondering if the circuit is being used or can be extracted out. Thanks!

 ```
# create circuits for Trotter Hamiltonians
        if accelerators is not None and (
            not isinstance(self.hamiltonian, self.hamiltonians.SymbolicHamiltonian)
            or solver != "exp"
        ):
            raise_error(
                NotImplementedError,
                "Distributed QAOA is implemented "
                + "only with SymbolicHamiltonian and "
                + "exponential solver.",
            )
        if isinstance(self.hamiltonian, self.hamiltonians.SymbolicHamiltonian):
            self.hamiltonian.circuit(1e-2, accelerators)
            self.mixer.circuit(1e-2, accelerators)
```

**Comment by renatomello** [comment]
> Sure, thanks for sharing your insights. I asked the question because I came across these lines of code in QAOA class and was wondering if the circuit is being used or can be extracted out. Thanks!
> 
> ```
> # create circuits for Trotter Hamiltonians
>        if accelerators is not None and (
>            not isinstance(self.hamiltonian, self.hamiltonians.SymbolicHamiltonian)
>            or solver != "exp"
>        ):
>            raise_error(
>                NotImplementedError,
>                "Distributed QAOA is implemented "
>                + "only with SymbolicHamiltonian and "
>                + "exponential solver.",
>            )
>        if isinstance(self.hamiltonian, self.hamiltonians.SymbolicHamiltonian):
>            self.hamiltonian.circuit(1e-2, accelerators)
>            self.mixer.circuit(1e-2, accelerators)
> ```

As you can see from this snippet you shared, the circuits are only created if `self.hamiltonian` is an instance of the `SymbolicHamiltonian` class, like I said it.

**Comment by NithyasriVS** [comment]
Thank you!

**Comment by renatomello** [comment]
@NithyasriVS actually, when the Hamiltonian is an instance of the `SymbolicHamiltonian` class, the circuits are already exposed. For instance,
```python
In [1]: import numpy as np
   ...: from qibo import models, hamiltonians
   ...: from qibo.symbols import *
   ...: # create XXZ Hamiltonian for four qubits
   ...: #hamiltonian = hamiltonians.XXZ(4)
   ...: hamiltonian = sum([X(0) * X(1), Y(0) * Y(1), 0.5 * Z(0) * Z(1)])
   ...: hamiltonian = hamiltonians.SymbolicHamiltonian(hamiltonian)
   ...: # create QAOA model for this Hamiltonian
   ...: qaoa = models.QAOA(hamiltonian)
   ...: # optimize using random initial variational parameters
   ...: # and default options and initial state
   ...: initial_parameters = 0.01 * np.random.random(4)
   ...: best_energy, final_parameters, extra = qaoa.minimize(initial_parameters, method="BFGS")
   ...: 
   ...: qaoa.hamiltonian.circuit(dt=0.1).draw()
   ...: print()
   ...: qaoa.mixer.circuit(dt=0.1).draw()
[Qibo 0.2.13|INFO|2024-10-24 13:17:48]: Using qibojit (cupy) backend on /GPU:0
q0: ─U─U─
q1: ─U─U─

q0: ─U─U─
q1: ─U─U─
```

**Comment by NithyasriVS** [comment]
Ah thank you! I was trying qaoa.circuit() and qaoa._circuit() instead! Thanks again
