### ISSUE TITLE
Copying circuit `wire_names`

### ISSUE THREAD

**Issue by csookim** [qiboteam/qibo#1524]
When copying the circuit, `wire_names is not transferred to the new circuit.

Minimal update to enable hw execution test.

**Comment by csookim** [comment]
@scarrazza Could you give permission to create a branch?

**Comment by scarrazza** [comment]
Retry now please.

**Comment by csookim** [comment]
Enabling int wire_names is necessary.

Instead of merging this, I will create a branch that includes both this update and the int `wire_names` update and test the branch on qrccluster.

Close this issue.
