### ISSUE TITLE
WARNING: Calculating the dense form of a symbolic Hamiltonian in qibo.models.evolution.AdiabaticEvolution

### ISSUE THREAD

**Issue by serg10mh** [qiboteam/qibo#1541]
When using qibo.models.evolution.AdiabaticEvolution with Symbolic Hamiltonians (both easy and problem hamiltonians), I get the following warning:

[Qibo 0.2.14|WARNING|2024-12-11 12:07:13]: Calculating the dense form of a symbolic Hamiltonian. This operation is memory inefficient.

It makes sense for this to occur in some other step such as: hamiltonian.ground_state(), but for AdiabaticEvolution the Trotter decomposition of the evolution operator will be calculated and used automatically if I am using Symbolic Hamiltonians, as stated in the documentation.

Then I do not understand the warning, why is the matrix form of the symbolic hamiltonian calculated if the TrotterizedExponential solver does not need it?

**Comment by alecandido** [comment]
@renatomello @BrunoLiegiBastonLiegi

**Comment by renatomello** [comment]
@serg10mh When running the Adiabatic Evolution without passing an initial state, the evolution defaults to starting at the ground state of the initial Hamiltonian $H_{0}$. To get this ground state, the function runs `h0.ground_state()` before starting the adiabatic evolution. That's where this warning is coming from and I don't think this is a bug. Please see https://github.com/qiboteam/qibo/blob/15fbaf96a040194c7f6f0f0adf3ba282dfe34606/src/qibo/models/evolution.py#L232

**Comment by serg10mh** [comment]
ok, that sounds logical. Sorry for the bug report, I thought the warning came from something else. Thank you very much for the clarification.

**Comment by alecandido** [comment]
Thanks @renatomello for the answer. @serg10mh if you believe the issue to be resolved, feel free to close it.
