### ISSUE TITLE
Computing circuit matrices.

### ISSUE THREAD

**Issue by igres26** [qiboteam/qibo#385]
As discussed in yesterdays meeting. It would be interesting to have an automatic way to transform a circuit, as in a sequence of gates applied to a quantum state, into its full matrix form.

Of course, this will only be possible for relatively few qubits, but can be interesting to see the full effect, of a circuit onto a quantum state.

This could be implemented with something like:

c = Circuit(nqubits)
c.add(gates....)
matrix_form = c.matrix()

I think this could be useful in some cases. 

Additionally, but not as pressing, if parametrized gates can be processed this way via symbols, it might help to further understand variational algorithms and the role of extra layers on initial parameters.

**Comment by renatomello** [comment]
This was solved by `Circuit.unitary()`, right @igres26?
