### ISSUE TITLE
Definition of fSim gate

### ISSUE THREAD

**Issue by AdrianPerezSalinas** [qiboteam/qibo#414]
Hi all, 

I have been woking with the `fSim` gate and seen that it is not defined as any other gate. Essentially, it performs the operation
`cos(theta)`, while all other gates compute `cos(theta / 2)`. 
What do you think about changing the definition?

**Comment by scarrazza** [comment]
As discussed, lets keep the definition as it is and observe if in future there are more evidence towards a definition update.
