### ISSUE TITLE
parallel tests hangs with tensorflow backend v2.5.0

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#418]
The `test_parallel.py` is failing when the backend is tensorflow (only v2.5.0).
The numpy and qibotf backends are passing the tests.

@stavros11 could you please confirm this happens for you? This is probably why our [CI](https://github.com/qiboteam/qibo/actions) is failing for linux.

**Comment by stavros11** [comment]
> @stavros11 could you please confirm this happens for you? This is probably why our [CI](https://github.com/qiboteam/qibo/actions) is failing for linux.

Yes, this happens for me with tf2.5 both for the qibotf and the tensorflow backend.

**Comment by scarrazza** [comment]
Could you please recheck qibotf? It works fine to me, the code hangs only with tensorflow.

**Comment by stavros11** [comment]
> Could you please recheck qibotf? It works fine to me, the code hangs only with tensorflow.

Indeed, qibotf works, it is only tensorflow that hangs. Sorry for the mistake in the previous post. I also think that only the first test of the two hangs with tensorflow, the one that tests `parallel_execution`. The second that tests `parallel_parametrized_execution` works for me with all backends.

**Comment by scarrazza** [comment]
Ok, I confirm your observation. I did a quick debug and the code hangs when calling the `circuit(state)`, if I run pytest with `taskset -c 0` both tests pass, so this sounds like the old thread problem we had before moving to openmp (I c++11 threads are created before the multiprocessing fork), if that is the case, then I believe the `qibo.set_threads(1)` is not working properly for tensorflow.
