### ISSUE TITLE
Set threads warning messages

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#442]
I was going to comment this on the qibojit PR but since this is merged I am writing here. I believe the following point is still open, right?

> @stavros11 let me put this info here, I believe we should include a warning message about `set_threads` when if the backend is tensorflow or numpy, in fact, I believe this function does not work as expected for these backends.

I was adding the warnings now, an issue though is that the [`set_threads` method ](https://github.com/qiboteam/qibo/blob/47ad4adc0674ba15578795e7f91c10b4e3823184/src/qibo/backends/__init__.py#L211) that is exposed to the user changes the threads for all created backends. This means that if numpy/tensorflow backends are created but a different backend (qibotf or qibojit) is active, then the numpy/tensorflow warnings will be raised if the user uses `set_threads`. @scarrazza, do you think we should modify `set_threads` to only change the threads of the active backend?

**Comment by scarrazza** [comment]
Thanks, indeed I had a look at the code and I agree that we should change the threads of the active backend.
