### ISSUE TITLE
OpenQASM parametrized gate conventions

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#452]
The parameter conventions we use for some gates in Qibo are different when compared to other libraries. For example compare the [U3 gate in Qibo](https://qibo.readthedocs.io/en/stable/qibo.html#qibo.abstractions.gates.U3) with the corresponding [gate in Qiskit](https://qiskit.org/documentation/stubs/qiskit.circuit.library.U3Gate.html). The difference is only a global phase which will not change the physics but will change the state vectors simulated and may confuse some users.

The issue mainly appears if one tries to build circuits using OpenQASM code. Particularly a Qasm command like:
```
u3(0.1,0.2,0.3) q[0];
```
will create a different gate in Qibo and Qiskit. Given that OpenQASM was published by IBM, I would guess that Qiskit's conventions should be considered the "correct" ones.

Two potential solutions to this are the following:
1. Change U2 and U3 gates completely to match Qiskit's conventions.
2. Keep our U2 and U3 as it is but change the Qasm parser (`Circuit.from_qasm`) to shift the parameters accordingly so that when creating these gates from Qasm the resulting circuit will be the same in Qibo, Qiskit and other libraries.

The second solution is slightly more complicated and may be more confusing.

**Comment by scarrazza** [comment]
I prefer the first solution as well. @igres26 do you see problems if we adopt the qiskit convention?

**Comment by igres26** [comment]
I am fine with adopting the Qiskit convention if that is what the community uses. It might have value to double-check other libraries to see if this is a wide spread convention or only a Qiskit one.

**Comment by scarrazza** [comment]
I had a look at our definition of U3 and we are using the original qasm paper expressions from https://arxiv.org/pdf/1707.03429.pdf, so I believe we can keep our original convention in order to avoid confusion, and eventually change that in the future if we identify clear advantages.
