### ISSUE TITLE
Installing qibo breaks installation from source

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#504]
**Describe the bug**

I noticed some strange behavior while trying to test qiboteam/qibotf#17 in my laptop. It seems that installing qibo using `python setup.py develop` breaks some package used by pip install / python setup.py making it impossible to install other libraries after.

**To Reproduce**

1. Create a clean python environment, for example using `python -m virtualenv test-env`
2. Install qibo from source using `python setup.py develop`. This ends with the following error:
```
error: pyparsing 3.0.4 is installed but pyparsing<3,>=2.0.2 is required by {'packaging'}
```
but qibo is still successfully installed and usable.
3. Try to install some other library, eg. qibojit, using `python setup.py develop`. This fails with the following error:
```
pkg_resources.ContextualVersionConflict: (pyparsing 3.0.4 (/home/stavros/PythonEnvs/test2-env/lib/python3.8/site-packages/pyparsing-3.0.4-py3.8.egg), Requirement.parse('pyparsing<3,>=2.0.2'), {'packaging'})
```
and qibojit is not usable. It is still possible to install libraries from pypi using pip, but not from source using `pip install .`.

It is the first time I notice something like this.

**Comment by mlazzarin** [comment]
It looks like a conflict between sub-dependencies. Take a look at https://github.com/pypa/packaging/pull/471 and https://github.com/pypa/packaging/issues/481.

**Comment by mlazzarin** [comment]
As a temporary fix, you can remove ``packaging==21.x`` and install ``packaging==21.0``.
