### ISSUE TITLE
Unitary Gate to support n-qubit gates

### ISSUE THREAD

**Issue by shangtai** [qiboteam/qibo#556]
I am trying to run QAOA but my mixer Hamiltonian is more complicated as it involves multiple target qubits.

```
from qibo import hamiltonians, models
from qibo.symbols import X, Y, Z

h_obj = hamiltonians.SymbolicHamiltonian(Z(0)*Z(1)+Z(1)*Z(2)+Z(2)*Z(3) + Z(3)*Z(0))
h_mixer = hamiltonians.SymbolicHamiltonian(X(0)*X(1))
qaoa = models.QAOA(h_obj, mixer = h_mixer)

```

The above code works. However, if I create a more complicated mixer as follows

```
h_mixer = hamiltonians.SymbolicHamiltonian(X(0)*X(1)*X(2))
qaoa = models.QAOA(h_obj, mixer = h_mixer)
```

I obtain the following `NotImplementedError: Unitary gate supports one or two-qubit gates when using custom operators, but 3 target qubits were given. Please switch to a different backend to execute this operation.`

I hope that we can allow more complicated mixer hamiltonian.

**Comment by DiegoGM91** [comment]
@shangtai which backend and version are you using?

I just tried the example on the `qibojit` backend, version 0.0.4, and it works (since custom multi-qubit kernels were added in this release).

**Comment by shangtai** [comment]
Hi @DiegoGM91 , thanks. I  tried `qibo.set_backend("qibojit")` May I know how do I set the version number for the backend?

**Comment by stavros11** [comment]
@shangtai you cannot set the version numbers as these depend on your qibo installation. Did you install qibo via pip? If yes, then you can do
```
pip install --upgrade pip
pip install --upgrade qibo
pip install --upgrade qibojit
```
to get the latest versions of qibo and qibojit.

Note that you don't need to do `qibo.set_backend("qibojit")` as qibojit will be the default backend (if it is installed).

**Comment by DiegoGM91** [comment]
Also, note that if you try the `qaoa.minimize()` method, it won't work now because the mixer Hamiltonian has support on 3 qubits, while the problem Hamiltonian has support on 4 qubits. We will fix this issue in future versions of `Qibo`.

For the time being, you can solve this by adding these lines to your code:

```
import numpy as np
from qibo.symbols import Symbol

def I(q):
    return Symbol(q, np.eye(2))

h_mixer = hamiltonians.SymbolicHamiltonian(X(0)*X(1)*X(2)*I(3))
```
