### ISSUE TITLE
Add generalized depolarizing channel

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#560]
It would be really helpful to have an implementation of the Depolarizing Channel like the one on [Qiskit](https://qiskit.org/documentation/stubs/qiskit.providers.aer.noise.depolarizing_error.html#qiskit.providers.aer.noise.depolarizing_error)

Note that the Pauli noise channel already implemented in Qibo is a special case of this channel. 
Also note that this is channel is global, acting on a system differently than the tensor product of single-qubit depolarizing channels

**Comment by scarrazza** [comment]
Thanks @renatomello, we are looking into this.
