### ISSUE TITLE
ValueError when probability vector sums to 1 up to machine precision

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#562]
```
from itertools import product
from qibo import gates
from qibo.models import Circuit
from qibo.hamiltonians import SymbolicHamiltonian
from qibo.symbols import I, X, Y, Z


def get_pauli_basis(qubits: int) -> list:
    ''' Returns list with all 4^qubits Pauli observables '''
    pauli_single = [I, X, Y, Z]
    aux = list(product(range(len(pauli_single)), repeat = qubits))
    observables = list()
    for row in aux:
        observable = 1
        for qubit, pauli in enumerate(row):
            observable = observable * pauli_single[pauli](qubit)
        observables.append(observable)
    return [SymbolicHamiltonian(pauli) for pauli in observables]


def get_probabilities(qubits: int, param: float = 1.) -> list:
    ''' Returns probability vector for a generalized depolarizing channel '''
    d = 2**qubits
    num_terms = d**2
    max_param = num_terms / (num_terms - 1)
    prob_identity = 1 - param / max_param
    prob_pauli = param / num_terms
    return [prob_identity] + [prob_pauli] * (num_terms - 1)


qubits = 2
param = 0.006

paulis = get_pauli_basis(qubits)
paulis = [pauli.dense.matrix for pauli in paulis]
paulis = list(product([(0, 1)], paulis))

probs = get_probabilities(qubits, param)

circuit = Circuit(qubits)
circuit.add((gates.UnitaryChannel(probs, paulis)))
```

This minimal code example raises the following:

```ValueError: UnitaryChannel probability sum should be between 0 and 1 but is 1.0000000000000002.```

**Comment by stavros11** [comment]
Thanks for finding this, I can reproduce it. @scarrazza I think we should relax this error to have some tolerance, eg. instead of `0 <= sum(p) < 1` check something like `-tol <= sum(p) < 1 + tol` where possibly `tol` is a backend attribute and depends on the active precision.

By the way this is one of the examples where #561 would make a difference performance if you run for more qubits, as in principle we could apply this channel using the Pauli gates, instead of doing the Kronecker products. 
Also, here you can avoid the `SymbolicHamiltonian` if you do the Kronecker products manually:
```Python
from itertools import product
from functools import reduce
import numpy as np
from qibo import matrices


def get_pauli_basis(qubits):
    pauli_single = [matrices.I, matrices.X, matrices.Y, matrices.Z]
    return [reduce(np.kron, row, 1) for row in product(pauli_single, repeat = qubits)]
```
This will return the same as `paulis = [pauli.dense.matrix for pauli in paulis]` in your code.

**Comment by renatomello** [comment]
Also, here you can avoid the `SymbolicHamiltonian` if you do the Kronecker products manually:
> 
> ```python
> from itertools import product
> from functools import reduce
> import numpy as np
> from qibo import matrices
> 
> 
> def get_pauli_basis(qubits):
>     pauli_single = [matrices.I, matrices.X, matrices.Y, matrices.Z]
>     return [reduce(np.kron, row) for row in product(pauli_single, repeat = qubits)]
> ```
> 
> This will return the same as `paulis = [pauli.dense.matrix for pauli in paulis]` in your code.

I've done something similar to this before, but the problem is that it scales really poorly since there are 4^nqubits observables and `nqubits - 1` kron products for each of them.

**Comment by scarrazza** [comment]
@stavros11 yes, we can probably use the approach implemented in `np.isclose` and keep a relative/absolute tolerance precision/backend dependent.
