### ISSUE TITLE
Simulations of large number of qubits and shallow depth circuits

### ISSUE THREAD

**Issue by bpcarlos** [qiboteam/qibo#571]
Many times we are required to run simulations of many qubits but shallow quantum circuits. We typically perform a state vector simulation taking into account the whole circuit and the total number of qubits. This, however, could be avoided in practice.

Would be great to have an automated Qibo tool to perform simulations with a large number of qubits (e.g. tens or hundreds) and shallow quantum circuits. This could be done by using a strategy related to the light-cone propagation of correlations in the circuit.

![lightcone](https://user-images.githubusercontent.com/19613198/161719283-ec648f5a-db8b-4eda-b1db-eb65d97e453f.png)

Imagine we want to compute the expectation value of a Hamiltonian composed of two-body operators `O`, i.e. `<\psi | O | \psi > = < 0 | U^\dag O U | 0 >`, acting on different qubits. The idea is to split the computation focusing on each operator `O` individually, noticing that most of the unitary `U` will annihilate with `U^\dag`. We then can compute `< \psi | O | \psi >` using the smaller quantum circuit inside the light cone.  Finally, we can compute the expectation value of the Hamiltonian by simply adding all the individual `< O >` values.

This indeed can be done by the user by constructing the smaller circuit inside the light cone for each of the operators `O` individually. However, it would be interesting to have an automated tool in Qibo that given the whole quantum circuit and operators `O`, performs the above computation. I think this may useful for many projects where the number of qubits is a bottleneck (as long as the circuit is shallow).

**Comment by DiegoGM91** [comment]
Nice one.

**Comment by stavros11** [comment]
Thanks for proposing this, sounds good to me. Here is a function that could serve as a starting point:
```py
def light_cone(circuit, observable_qubits):
    """Reduces circuit to the qubits relevant for an observable.
    
    Args:
        circuit (qibo.models.Circuit): Complete circuit.
        observable_qubits (Iterable): Qubit ids that the observable 
            of interest has support on.

    Returns:
        Circuit that contains only the qubits that are required 
        for calculating expectation values of this observable.
    """
    # Find which qubits are in the light cone
    qubits = set(observable_qubits)
    for gate in reversed(circuit.queue):
        gate_qubits = set(gate.qubits)
        # if the gate involves any qubit included in the 
        # light cone, add all its qubits in the light cone
        if gate_qubits & qubits:
            qubits |= gate_qubits
    
    # Create a new circuit ignoring gates that are not in the light cone
    qubit_map = {q: i for i, q in enumerate(sorted(qubits))}
    kwargs = dict(circuit.init_kwargs)
    kwargs["nqubits"] = len(qubits)
    subcircuit = circuit.__class__(**kwargs)
    for gate in circuit.queue:
        if set(gate.qubits).issubset(qubits):
            # This part can be probably be delegated to the existing ``gate._on_qubits``
            if gate.is_controlled_by:
                # map original qubit ids to the ids in the reduced circuit
                targets = (qubit_map.get(q) for q in gate.target_qubits)
                controls = (qubit_map.get(q) for q in gate.control_qubits)
                new_gate = gate.__class__(*targets, **gate.init_kwargs)
                subcircuit.add(new_gate.controlled_by(*controls))
            else:
                gatequbits = (qubit_map.get(q) for q in gate.qubits)
                subcircuit.add(gate.__class__(*gatequbits, **gate.init_kwargs))
    return subcircuit
```
This calculates the "light cone" circuit corresponding to a given big circuit and the list of qubits that O acts on. For example for a typical variational circuit with one layer:
```py
from qibo import gates
from qibo.models import Circuit


nqubits = 20
c = Circuit(nqubits)
c.add(gates.RY(i, theta=0) for i in range(nqubits))
c.add(gates.CZ(i, i + 1) for i in range(0, nqubits - 1, 2))
c.add(gates.RY(i, theta=0) for i in range(nqubits))
c.add(gates.CZ(i, i + 1) for i in range(1, nqubits - 1, 2))
c.add(gates.CZ(0, nqubits - 1))
```
the light cone for an O acting on qubits 4 and 5 would be
```py
sc = light_cone(c, [4, 5])
```
which is a 6-qubit circuit (regardless of how big the original circuit is). 

If we follow this approach, we could add this as a circuit method, eg. one would do `circuit.light_cone([4, 5])` to get the reduced circuit. We still need think of an API to combine this with Hamiltonians and expectation values, so that it is fully automatic from the user perspective.

**Comment by bpcarlos** [comment]
Thanks, @stavros11! I played around with it, it works perfectly except for 1 detail. The circuit in the light cone it indeed has the number of required qubits, however, there are some gates that do not need to be included. We have to discard as well the gates outside the light cone, even if they pertain to the qubits inside. Let me put an example using your function:

```
nqubits = 20
c = Circuit(nqubits)
for i in range(1):
    c.add(gates.RY(i, theta=0) for i in range(nqubits))
    c.add(gates.CZ(i, i + 1) for i in range(0, nqubits - 1, 2))
    c.add(gates.RY(i, theta=0) for i in range(nqubits))
    c.add(gates.CZ(i, i + 1) for i in range(1, nqubits - 1, 2))

sc = light_cone(c, [11,12])

print(c.draw())
print(sc.draw())
```

The final RY gates in `sc` on qubits 0 and 1 are not needed, since they are outside the light cone. That is, we do not have to simply cut the larger circuit into a small one, but also exclude the gates outside the light cone that are affecting those qubits.

**Comment by bpcarlos** [comment]
perhaps it is clearer with this image (orange cone)

![Dibujo](https://user-images.githubusercontent.com/19613198/162384877-834c0b5f-3446-495d-adb4-b545fa555455.png)

**Comment by bpcarlos** [comment]
Also I believe it would be great to know to which new labels (qubits) correspond the observables in the new light cone circuit

**Comment by stavros11** [comment]
@bpcarlos thanks for checking. I believe the redundant gates issue is solved in the following:
```py
def light_cone(circuit, observable_qubits):
    """Reduces circuit to the qubits relevant for an observable.
    
    Args:
        circuit (qibo.models.Circuit): Complete circuit.
        observable_qubits (Iterable): Qubit ids that the observable 
            of interest has support on.

    Returns:
        subcircuit (qibo.models.Circuit): Circuit that contains only 
            the qubits that are required for calculating expectation 
            involving the given observable qubits.
        qubit_map (dict): Dictionary mapping the qubit ids of the original
            circuit to the ids in the new one.
    """
    # original qubits that are in the light cone
    qubits = set(observable_qubits)
    # original gates that are in the light cone
    gates = []
    for gate in reversed(circuit.queue):
        gate_qubits = set(gate.qubits)
        if gate_qubits & qubits:
            # if the gate involves any qubit included in the 
            # light cone, add all its qubits in the light cone
            qubits |= gate_qubits
            gates.append(gate)
    
    # Create a new circuit ignoring gates that are not in the light cone
    qubit_map = {q: i for i, q in enumerate(sorted(qubits))}
    kwargs = dict(circuit.init_kwargs)
    kwargs["nqubits"] = len(qubits)
    subcircuit = circuit.__class__(**kwargs)
    for gate in reversed(gates):
        # This part can be probably be delegated to the existing ``gate._on_qubits``
        if gate.is_controlled_by:
            # map original qubit ids to the ids in the reduced circuit
            targets = (qubit_map.get(q) for q in gate.target_qubits)
            controls = (qubit_map.get(q) for q in gate.control_qubits)
            new_gate = gate.__class__(*targets, **gate.init_kwargs)
            subcircuit.add(new_gate.controlled_by(*controls))
        else:
            gatequbits = (qubit_map.get(q) for q in gate.qubits)
            subcircuit.add(gate.__class__(*gatequbits, **gate.init_kwargs))
    
    return subcircuit, qubit_map
```
Please check that this works as expected in your examples as it is not rigorously tested. 

I also return the `qubit_map` which is a dictionary mapping the qubit numbers of the original circuit to the numbers in the light cone circuit. I believe this is what is needed to calculate the observable, but if you need to invert this, you can do:
```py
{v: k for k, v in qubit_map.items()}
```

**Comment by bpcarlos** [comment]
Works perfect, thanks @stavros11
