### ISSUE TITLE
customize loss function for QAOA

### ISSUE THREAD

**Issue by shangtai** [qiboteam/qibo#576]
**Is your feature request related to a problem? Please describe.**

qaoa uses expectation as a loss function.  We would like generalize the loss function for qaoa.

    def _loss(params, qaoa, hamiltonian):
        qaoa.set_parameters(params)
        state = qaoa(initial_state)
        return hamiltonian.expectation(state)

As of now, the loss function is based the expectation, can a user use their own loss function for QAOA such as cvar? 

**Describe the solution you'd like**

Perhaps a function that let us pass in a loss function so that QAOA can optimize based on the loss function.

**Comment by shangtai** [comment]
To customize the loss funcion, I am thinking of performing the following changes: 

In line 408 of variational.py, we introduce another argument, perhaps a string or a number, to let the user change the loss function and change the output: 

        def _loss(params, qaoa, hamiltonian):
            qaoa.set_parameters(params)
            state = qaoa(initial_state)
            return hamiltonian.expectation(state)

and add some alternative loss functions in the hamiltonians.py.

**Comment by scarrazza** [comment]
One possibility is to:
- Modify the signature of the minimize function by including a `loss=None` in: https://github.com/qiboteam/qibo/blob/92ded014042269b5b64ef1574b2a7f9a3218d0e0/src/qibo/models/variational.py#L372
- in line 408 perform a conditional if/else to check if `loss is None`, and assign the proper object.

**Comment by scarrazza** [comment]
@shangtai can we close this?

**Comment by shangtai** [comment]
Sure, I will do a pull request when things are more ready :)
