### ISSUE TITLE
Optimization of Pauli Basis representation

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#580]
What I would like to know is if there's a built-in way of representing states in the Pauli basis and if there's an efficient way of getting that representation. Currently I'm doing something similar to this code below:

```python3
from itertools import product
from functools import reduce
from numpy import pi, log10, asarray, kron
from numpy.random import rand
from qibo import set_backend, matrices
set_backend('numpy')
from qibo.models import Circuit
from qibo import gates as gt


def get_random_circuit(qubits: int, depth: int, density_matrix: bool = False):
    circuit = Circuit(qubits, density_matrix = density_matrix) if density_matrix else Circuit(qubits)
    for _ in range(depth):
        for qubit in range(qubits):
            circuit.add(gt.U3(qubit, 0, 0, 0))
        cnots_even = asarray([[k, k + 1] for k in range(0, qubits - 1, 2)])
        cnots_odd = asarray([[k, k + 1] for k in range(1, qubits - 1, 2)])
        for row in cnots_even:
            circuit.add(gt.CNOT(*row))
        for row in cnots_odd:
            circuit.add(gt.CNOT(*row))
    return circuit


def generate_phases(qubits: int, depth: int, local_state = None):
    all_phases = list()
    for _ in range(depth):
        phases = rand(qubits, 3)
        phases[:, 0] = phases[:, 0] * pi
        phases[:, 1] = phases[:, 1] * 2*pi
        phases[:, 2] = phases[:, 2] * 2*pi
        all_phases.append(phases)
    return asarray(all_phases)


def get_state_sample(qubits: int, depth: int):
    phases = list()
    aux = generate_phases(qubits, depth)
    for row in aux:
        for phases_list in row:
            phases.append(list(phases_list))
    return phases


qubits = 7
d = 2**qubits
depths = [5, 6]
samples = int(1e3)

pauli_single = asarray([matrices.I, matrices.X, matrices.Y, matrices.Z])
pauli_basis = [reduce(kron, row) for row in product(pauli_single, repeat = qubits)]

for depth in depths:
    circuit = get_random_circuit(qubits, depth)
    sampled_S = list()
    for sample in range(samples):
        if sample % 1 == 0:
            print(f'\rQubits: {qubits}, Total Samples: 1e{int(log10(samples))}, Depth: {depth}, ' \
                + f'Pctg: {round(100 * sample / samples, 1)}%', end = '', flush = True)
        phases = get_state_sample(qubits, depth)
        circuit.set_parameters(phases)
        pauli_basis_representation = asarray([(circuit().expectation(pauli))**2 for pauli in pauli_basis])
```

Since for the problem I'm interested in I have to sample thousands of states and represent them all of them in the Pauli Basis, this naive implementation scales really badly.

Anyone here would have a better idea of how to use Qibo to the fullest in order to optimize this?

Thank you in advance

**Comment by stavros11** [comment]
Some attempts to make this calculation faster:

i) In the construction of `pauli_basis_representation` the `circuit()` that is inside the list comprehension will be executed `len(pauli_basis)` which is a large number. Instead you can execute the circuit once outside the loop and reuse the final state for the expectation calculations:
```py
circuit.set_parameters(phases)
state = circuit()
pauli_basis_representation = asarray([(state.expectation(pauli))**2 for pauli in pauli_basis])
```

ii) an alternative way to do this calculation without creating the 2^qubits x 2^qubits matrices in `pauli_basis` is the following:
```py
previous_string = qubits * ("I")
unitaries = []
for current_string in product(["I", "X", "Y", "Z"], repeat=qubits):
    qb, matlist = [], []
    for i, (g1, g2) in enumerate(zip(previous_string, current_string)):
        if g1 != g2:
            qb.append(i)
            matlist.append(getattr(matrices, g2) @ getattr(matrices, g1))
    if qb:
        matrix = reduce(kron, matlist)
        unitaries.append(gt.Unitary(matrix, *qb))
    previous_string = current_string

circuit = get_random_circuit(qubits, depth)
for sample in range(samples):
    if sample % 1 == 0:
        print(f'\rQubits: {qubits}, Total Samples: 1e{int(log10(samples))}, Depth: {depth}, ' \
            + f'Pctg: {round(100 * sample / samples, 1)}%', end = '', flush = True)
    phases = get_state_sample(qubits, depth)
    circuit.set_parameters(phases)
    state = circuit().numpy()
    tstate = np.copy(state)
    representation = [np.sum(np.abs(state) ** 2) ** 2]
    for gate in unitaries:
        tstate = gate(tstate)
        representation.append(np.conj(tstate).dot(state) ** 2)
    pauli_basis_representation = asarray(representation)
```
For qubits=7, depth=5 and samples=10 this takes 3sec in my laptop, while the original implementation after the circuit correction takes 15sec.

**Comment by renatomello** [comment]
Thank you for the quick and helpful answer. I'' test out your suggestions.

One question though:
> For qubits=7, depth=5 and samples=10 this takes 3sec in my laptop, while the original implementation after the circuit correction takes 15sec.
Which backend you used? Because I ran my version of the code for qubits=7, depth=5 and samples=1000 and it took ~20h on numpy backend.

**Comment by stavros11** [comment]
> Which backend you used? Because I ran my version of the code for qubits=7, depth=5 and samples=1000 and it took ~20h on numpy backend.

I used the qibojit backend on CPU (numba) for these tests which may be slightly faster than numpy, but most likely the difference is small for 7-qubit circuits. The 15sec for 10 samples is after the correction (i) I wrote above (moving the `circuit()` outside the loop). If I extrapolate this to 1000 samples, it should take around 12h which is better as we avoid many circuit executions. The other method should take 4h.

**Comment by renatomello** [comment]
> > Which backend you used? Because I ran my version of the code for qubits=7, depth=5 and samples=1000 and it took ~20h on numpy backend.
> 
> I used the qibojit backend on CPU (numba) for these tests which may be slightly faster than numpy, but most likely the difference is small for 7-qubit circuits. The 15sec for 10 samples is after the correction (i) I wrote above (moving the `circuit()` outside the loop). If I extrapolate this to 1000 samples, it should take around 12h which is better as we avoid many circuit executions. The other method should take 4h.

OK, thank you. I'll try it out
