### ISSUE TITLE
Check `.compile` performance

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#607]
Check if `.compile` is really needed with the latest tensorflow release. If not, we can remove it.

**Comment by scarrazza** [comment]
@andrea-pasquale could you please give a try and let us know if there is some advantage?

**Comment by andrea-pasquale** [comment]
Of course, @scarrazza.
Do you want me to check this directly within the PRs that implement the refactor (for example in the `abstrtnp` branch), or in the master branch?

**Comment by andrea-pasquale** [comment]
Here are some results on CPU up to 20 qubits (I slightly modified the code from the qibojit-benchmark repository):

Dry run time:
![qibo_scaling_qft_total_dry_time_None](https://user-images.githubusercontent.com/49183315/177206473-ba7e7d11-1aca-446b-9d04-e0600cb427e4.jpg)

Simulation time:
![qibo_scaling_qft_simulation_times_mean_None](https://user-images.githubusercontent.com/49183315/177206483-e0a08bf6-aa75-4502-83e3-665b8b663d13.jpg)

From this results I think that we should keep `.compile`.

**Comment by scarrazza** [comment]
Thanks @andrea-pasquale it is clear, however it looks strange to me that a qft with 30 qubits takes only 1e-3s to execute, could you please check if results are correct?

**Comment by andrea-pasquale** [comment]
The maximum number of qubits that I've tested is 20 not 30, so I think that they should be correct.
If you want I can increase the number of qubits, I went up to 20 because I was testing this on my laptop.

**Comment by scarrazza** [comment]
Thanks @andrea-pasquale, indeed, and I need a high dpi screen.
