### ISSUE TITLE
docs build are failing

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#625]
Readthedocs is using the latest sphinx and plugins. The compilation is failing with:
```
Extension error (sphinx_markdown_tables):
Handler <function process_tables at 0x7f705b63fcb0> for event 'source-read' threw an exception (exception: __init__() missing 1 required positional argument: 'config')
```

**Comment by stavros11** [comment]
This will cause CI issues in all new developments and releases. @scarrazza do you think that we should remove the old tables from the docs and remove this dependency?

**Comment by scarrazza** [comment]
I think so, at this point they are obsolete.
