### ISSUE TITLE
Implement realistic `NoiseModel`

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibo#637]
Given that we are almost done with the characterization of the quantum devices in Qibolab, it would be interesting to have the possibility to emulate these systems directly in Qibo using a noise model. Qiskit has already a similar  [feature](https://qiskit.org/documentation/stubs/qiskit.providers.aer.noise.NoiseModel.from_backend.html#qiskit.providers.aer.noise.NoiseModel.from_backend). They are creating a noise model where the error parameters are based on physical quantities such as T1, T2, etc...
In order to implement this we will surely need to have the depolarizing channel in Qibo (#560). Since we already have a Noise Model class in Qibo I think that it should not be that difficult to add this feature. The only problem is that we may require the user to install Qibolab in order to build correctly these type of noise models, maybe it is also possible to find a workaround for this.

**Comment by scarrazza** [comment]
@LucaZilli following our discussion yesterday, let me summarize the next steps:

* Noise model prototyping:
- [ ] introduce a metric to measure the distance between real hardware output and noise model
- [ ] compare qibo and qiskit noise models in a variation circuit setup so we can increase statistics on different circuit layouts. 
- [ ] implement fitting procedure using qibo's optimizer method.

* API
- [ ] propose an API that integrates with the current `NoiseModel` object.
- [ ] document usage with examples
