### ISSUE TITLE
Unpredictable behaviour when setting initial state for circuit.light_cone()

### ISSUE THREAD

**Issue by GibbsJR** [qiboteam/qibo#646]
When I repeatedly execute the following code:

```
from qibo import gates
from qibo.models import Circuit
import numpy as np

n = 12

def lightconed_circuit(q):

  c = Circuit(n, density_matrix=True)
  
  dt = 0.1
  
  for i in range(0, n-1, 2):
    c.add(gates.RXX(i, (i+1)%n, theta=dt))
    c.add(gates.RYY(i, (i+1)%n, theta=dt))
    
  for i in range(1, n-1, 2):
    c.add(gates.RXX(i, (i+1)%n, theta=dt))
    c.add(gates.RYY(i, (i+1)%n, theta=dt))

  sc = c.light_cone(q)

  return sc


sc = lightconed_circuit(6)

print(sc[0].draw())
print()
# makes 4 qubit circuit
reduced_q = 4

initial_state = np.zeros(2**reduced_q)
initial_state[1] = 1
print(sc[0](initial_state).state())
```

The output seems to widely vary, from a sensible looking answer, to an array full of nan's or entries all ~e+250

1:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/109437810/191480134-e9f930a8-6908-4d30-9d3c-402bc1d45fd3.png">

2:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/109437810/191480208-ed9c7a84-7d77-417e-83e0-08e79f3fdb2e.png">

3:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/109437810/191480067-702059a7-59da-43aa-9482-40d4bab612cd.png">

4:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/109437810/191480363-5ec5edd2-d750-4c74-bdbc-ba4ecff13814.png">

Am I using this functionality incorrectly?

**Comment by JoexGibbs** [comment]
Ah this makes sense, thanks for pointing that out.

Changing the initial state as below solves the error:

```
from qibo import gates
from qibo.models import Circuit
import numpy as np

n = 12

def lightconed_circuit(q):

  c = Circuit(n, density_matrix=True)
  
  dt = 0.1
  
  for i in range(0, n-1, 2):
    c.add(gates.RXX(i, (i+1)%n, theta=dt))
    c.add(gates.RYY(i, (i+1)%n, theta=dt))
    
  for i in range(1, n-1, 2):
    c.add(gates.RXX(i, (i+1)%n, theta=dt))
    c.add(gates.RYY(i, (i+1)%n, theta=dt))

  sc = c.light_cone(q)

  return sc


sc = lightconed_circuit(6)

print(sc[0].draw())
print()
# makes 4 qubit circuit
reduced_q = 4

initial_state = np.zeros((2**reduced_q, 2**reduced_q))
initial_state[1, 1] = 1
print(np.around(sc[0](initial_state).state(), 3))
```

However, changing _reduced_q_ to a value other than 4 shouldn't be valid as the input state will have incorrect dimensions, however it runs without error for _reduced_q_ = 3 or 5 but gives a nonsense answer. Maybe a test should be added to check the dimensions of the input state are correct?

**Comment by stavros11** [comment]
> However, changing _reduced_q_ to a value other than 4 shouldn't be valid as the input state will have incorrect dimensions, however it runs without error for _reduced_q_ = 3 or 5 but gives a nonsense answer. Maybe a test should be added to check the dimensions of the input state are correct?

You are right. We should add a check that the input state has proper dimensions possibly including whether it is a density matrix or no, so that it is easier to understand what is the issue.

**Comment by scarrazza** [comment]
@stavros11 shall we close this?

**Comment by stavros11** [comment]
I just gave another try and it seems that with qibojit it is possible to execute circuits using initial states with the wrong number of qubits. For example the following:
```py
from qibo import gates
from qibo.models import Circuit
import numpy as np
import qibo

qibo.set_backend("qibojit")
#qibo.set_backend("numpy")

c = Circuit(2, density_matrix=True)
c.add(gates.H(0))

n = 5

initial_state = np.zeros((2**n, 2**n))
initial_state[1, 1] = 1
final_state = c(initial_state).state()
print(np.around(final_state, 3))
print(final_state.shape)
```
works, even though we are using a 5-qubit density matrix as initial state on a 2-qubit circuit, and I believe it leads to a wrong result. With numpy, this leads to a shape error (as expected).

This is not directly related to this issue, however I would still try to address before closing. The simplest is probably to raise an error if an initial state of the wrong shape is given so that execution is blocked for all backends. I can try to open a PR for this.
