### ISSUE TITLE
Missing iSWAP gate and some gates documentation

### ISSUE THREAD

**Issue by Simone-Bordoni** [qiboteam/qibo#705]
I noticed that there is not an iSWAP gate implemented in Qibo, this is an important gate as may be a native gate (highly used in the transpiler).
Moreover there is no documentation for RXX, RYY and RZZ gates.

**Comment by scarrazza** [comment]
@Simone-Bordoni thanks for pointing this out. The gates are documented but not rendered in sphinx. May I ask you to open 2 PRs, the first containing the sphinx include instructions to render the R* and another with the iSWAP gate?
