### ISSUE TITLE
Building error due to "test_dill.py" from master branch

### ISSUE THREAD

**Issue by ihpcdingwj** [qiboteam/qibo#713]
We are developing qcnn model in qcnn2 branch. All run well, except error from "test_dill.py", which is inherited from the master branch. In order to pass the building, we delete "test_dill.py" in qcnn2 branch. However, in pull request, the error still pops up due to this file.

**Comment by stavros11** [comment]
I believe this issue has already been fixed. I see that the qcnn2 branch is 345 commits behind master. Could you please merge the latest master to your branch and retry? The error should disappear.
