### ISSUE TITLE
Mølmer-Sørenson gate

### ISSUE THREAD

**Issue by MarcoSciorilli** [qiboteam/qibo#732]
In order to ease benchmarking and testing algorithms to run on IonQ hardware, it would be very useful to have their native gates already implemented in qibo.
Personally, I'm particularly interested in the parameterized Mølmer-Sørenson gate.
A list and description of their gates can be found at: https://ionq.com/docs/getting-started-with-native-gates

**Comment by andrea-pasquale** [comment]
Thanks for opening this issue @MarcoSciorilli.
I can take care of implementing these new gates in Qibo.

In the meantime if you want to use already these gates in Qibo you can do it using the [`Unitary`](https://qibo.readthedocs.io/en/latest/api-reference/qibo.html#qibo.gates.Unitary) gate. 

Here is a possible implementation of the `GPI` gate:

```python
import numpy as np
from qibo import models, gates


def GPI(q, theta):
    matrix = np.array([[0, np.exp(-1.j * theta)], [np.exp(1.j * theta), 0]])
    return gates.Unitary(matrix, q)

circuit = models.Circuit(1)
circuit.add(GPI(0, np.pi))
circuit()

```

This procedure can easily be generalized also for multiqubits gates.
