### ISSUE TITLE
Update deprecated actions

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#753]
Node.js requires updated versions for several actions in our workflows.

**Comment by AleCandido** [comment]
While qiboteam/workflows#22 does not address the whole issue in the title, I believe it solves the one in the OP

> Node.js requires updated versions for several actions in our workflows.

It seems to me that Node is only used in workflows related to the website.

However, please @Edoardo-Pedicillo keep going attempting the transition of
- https://github.com/qiboteam/qibo/blob/master/.github/workflows/rules.yml
- https://github.com/qiboteam/qibo/blob/master/.github/workflows/deploy.yml

to the workflows repository, as described in qiboteam/workflows#11

**Comment by AleCandido** [comment]
The Node.js has been updated in the relevant actions, the rest of the migration it is tracked by #763
