### ISSUE TITLE
Bugged workflow prevented Pylint errors

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibo#776]
In the current workflow, Python to be linted are selected with a double star glob:
https://github.com/qiboteam/qibo/blob/9706cce06ee713187df705cc48eb30fe5ac23bad/.github/workflows/rules.yml#L34-L35

But in Bash, the double star is equivalent to a single star, unless `shopt -s globstar` is used (and it is not, by default).
https://stackoverflow.com/a/28199633/8653979

However, the simple solution is to just truncate the path: selecting only `src/` Pylint will already look recursively for the files.
I believe that Pylint is already mostly looking at Python files, but in case it would catch also something else, we will find away to whitelist those files later on (for the time being, nothing seems to affected in this sense).

The result of replacing the glob is that new errors have been found, and now they have to be fixed (possibly the authors of the code affected should either fix it, or explicitly tell to ignore the lint).

**Comment by AleCandido** [comment]
Here the current errors:
https://github.com/qiboteam/qibo/actions/runs/4071750815/jobs/7013973082#step:5:13
```
************* Module qibo.models.error_mitigation
src/qibo/models/error_mitigation.py:319:15: E1101: Instance of 'list' has no 'T' member (no-member)
************* Module qibo.models.circuit
src/qibo/models/circuit.py:973:20: E1101: Instance of 'CompiledExecutor' has no 'executor' member (no-member)
src/qibo/models/circuit.py:976:32: E1101: Instance of 'CompiledExecutor' has no 'result' member (no-member)
************* Module qibo.backends.numpy
src/qibo/backends/numpy.py:399:20: E1111: Assigning result of a function call, where the function has no return (assignment-from-no-return)
************* Module qibo.hamiltonians.hamiltonians
src/qibo/hamiltonians/hamiltonians.py:562:26: E1101: Instance of 'HamiltonianTerm' has no 'factors' member (no-member)
src/qibo/hamiltonians/hamiltonians.py:567:19: E1101: Instance of 'HamiltonianTerm' has no 'factors' member (no-member)
src/qibo/hamiltonians/hamiltonians.py:567:44: E1101: Instance of 'HamiltonianTerm' has no 'factors' member (no-member)
************* Module qibo.hamiltonians.adiabatic
src/qibo/hamiltonians/adiabatic.py:162:12: E1102: self.schedule is not callable (not-callable)
```

**Comment by scarrazza** [comment]
Thanks @AleCandido, could you and/or @Edoardo-Pedicillo apply this changes in #770?
