### ISSUE TITLE
When using .copy() method on circuit the depth changes of original circuit

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibo#783]
Copying a circuit with the .copy() method alters the attribute ``.queue.moments`` which results in a different depths.

```python
from qibo import gates, models
nqubits = 3
circuit = models.Circuit(nqubits)
circuit.add(gates.X(0))
circuit.add(gates.X(1))
circuit.add(gates.H(0))
circuit.add(gates.H(0))
print(circuit.depth) # -> 3
print(circuit.queue.moments)
print('----- copy circuit, original circuit was altered -----')
copied_circuit = circuit.copy(deep = False)
print(circuit.depth) # -> 6
print(circuit.queue.moments)
print('----- copied circuit  -----')
print(copied_circuit.depth) # -> 6
print(copied_circuit.queue.moments)
```

Also, when using the ``copy.deepcopy`` python module, the copied circuit has the same problem, but the circuit itself was not altered:

```python
from qibo import gates, models
from copy import deepcopy
nqubits = 3
circuit = models.Circuit(nqubits)
circuit.add(gates.X(0))
circuit.add(gates.X(1))
circuit.add(gates.H(0))
circuit.add(gates.H(0))
print(circuit.depth) # -> 3
print(circuit.queue.moments) 
print('----- copy.deepcopy circuit -----')
deepcopy_circuit = deepcopy(circuit)
print(deepcopy_circuit.queue.moments)
print(deepcopy_circuit.depth) # -> 6
print('--------- no change in original circuit ---------')
print(circuit.depth) # -> 3
print(circuit.queue.moments)
```

Only when setting ``circuit.copy(deep = True)`` the copy process works.

**Comment by wilkensJ** [comment]
In randomized benchmarking (implemented in `qibocal`) the depth of the circuit is crucial to store, but if the circuit is copied the depth changes, which is bad. And the copy is necessary because the circuit has to be stored via dumping into a pickle file which is only possible if it was not executed. Unfortunately, another bug (see issue #784) also prevents this, which could be linked to this issue.

**Comment by MatteoRobbiati** [comment]
For now I have solved this problem by removing the shallow copying procedure from `circuit.copy(deep=False)` and by doing the shallow copies of the `queue` elements inside the `self._shallow_copy` function:

```python
    def _shallow_copy(self):
        """Helper method for :meth:`qibo.models.circuit.Circuit.copy`
        and :meth:`qibo.core.circuit.Circuit.fuse`."""
        new_circuit = self.__class__(**self.init_kwargs)
        new_circuit.parametrized_gates = _ParametrizedGates(self.parametrized_gates)
        new_circuit.trainable_gates = _ParametrizedGates(self.trainable_gates)
        new_circuit.measurements = self.measurements
        # HERE NEW COPIES
        new_circuit.queue.nqubits = self.queue.nqubits
        new_circuit.queue.moments = self.queue.moments.copy()
        new_circuit.queue.moment_index = self.queue.moment_index.copy()
        new_circuit.queue.nmeasurements = self.queue.nmeasurements
        return new_circuit
```

This solution is certainly not very elegant, plus I would like you to confirm that it performs a shallow copy of the `_Queue` class @wilkensJ, @stavros11. 

I will also add two more details about the copy error that occurs using `copy.copy(self.queue)`:

1. also `self.queue.moment_index` is modified: it seems that using `copy.copy` on lists of lists results in this;
2. the layout of the new circuit is always the same:

```
X1--H1--H2--X1--H1--H2
X2--X2----------------
----------------------
```

If you agree with my solution, I can open a PR.

**Comment by MatteoRobbiati** [comment]
I am sorry @stavros11, I have only just seen your PR #805!
