### ISSUE TITLE
Pytest not running only selected file

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#786]
When using `pytest`, we are unable to run tests for only one test file.

As @stavros11 mentioned on Teams, this seems to come from the flag `--pyargs qibo` in [pyproject.toml](https://github.com/qiboteam/qibo/blob/master/pyproject.toml)

**Comment by scarrazza** [comment]
Yes, this is expected, you should launch pytest from outside the qibo directory.

**Comment by renatomello** [comment]
Before I was always able to run it either from the local cloned repository or directly from the `qibo/src/qibo/tests/`, which is in line with what was presented in the Documentation presentation that was given a couple of months ago.

Now it's only possible when removing the aforementioned flag. What's the right way to do it?

**Comment by scarrazza** [comment]
@renatomello this behaviour is being fixed in https://github.com/qiboteam/qibolab/pull/301 and will be ported to this repo too.

**Comment by renatomello** [comment]
I see. Thank you.
