### ISSUE TITLE
Sphinx compiling from local installation instead of cloned repository

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#790]
When compiling documentation with `make html` inside `qibo/doc/`, Sphinx compiles from the installed version of Qibo instead using the files in the cloned repository.

Is it supposed to be this way or is it a bug?

**Comment by scarrazza** [comment]
I would say yes, it is expected, ideally we should have a dev environment with qibo installed using `pip install -e .` so when sphinx imports qibo, it uses the development branch.

**Comment by renatomello** [comment]
Thank you for the explanation.
