### ISSUE TITLE
Outdated QASM generation

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibo#791]
Qibo is generating OpenQASM 2.0 code, but the current version is 3.0 since almost a couple of years, and it is the only version currently available online. At least the only one directly reachable from the home page:
https://openqasm.com/

Example:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/10830876/219013536-73e2186d-4ecb-45fe-af70-bcb3fb79d7a6.png">

Page 9, https://arxiv.org/pdf/2104.14722.pdf

```c
// Generated by QIBO 0.1.11
OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
h q[0];
```

Found in the context of https://github.com/qiboteam/qibotn/pull/8

**Comment by scarrazza** [comment]
Yes, we had some discussions about this in past, in particular when we started in 2020. The major limitation was that other codes where not compatible with v3, therefore we decide to use v2.

**Comment by AleCandido** [comment]
Ok, so maybe we could reassess the situation three years later.

For what I know, in 2020 the default docs could have been about v2, and they have changed by now...

**Comment by visagim** [comment]
Hi, I was wondering if there were any ongoing plans to add support for OpenQASM 3.0 to qibo anytime soon? (specially in circuit.to_qasm() )

**Comment by scarrazza** [comment]
Yes, but we need volunteers to tackle this implementation at the moment.

**Comment by AleCandido** [comment]
In order not to reinvent the wheel, there is a Python package available to parse OpenQASM, from the string to [its objects](https://github.com/openqasm/openqasm/blob/main/source/openqasm/openqasm3/ast.py).

The package is from the authors of OpenQASM itself, so it is kind of official (and officially a Qiskit project), but this means that there exists an official package doing the parsing (with ANTLR), and we just have to translate from an objects' tree to a circuit.

Unfortunately, they have no docs for the Python package, other than the [docstrings](https://github.com/openqasm/openqasm/blob/07b41d01042a35768c4e26a83ce52b97961d0b84/source/openqasm/openqasm3/ast.py#L136) and an [`index` file](https://github.com/openqasm/openqasm/blob/main/source/openqasm/docs/index.rst), that is a bit poor...
