### ISSUE TITLE
Activate merge queue

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#792]
The merge queue is active for this repository, however I believe we should update the workflow to include the following key:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Comment by AleCandido** [comment]
@Edoardo-Pedicillo can you please take care of this?

**Comment by Edoardo-Pedicillo** [comment]
Yes, it sounds interesting.
