### ISSUE TITLE
Circuit serialization

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibo#809]
For `Circuit` class, we could apply what described in https://github.com/qiboteam/qibo/pull/804#issuecomment-1443186870.

For the evaluated circuits (i.e. arrays), we just have to make sure that NumPy file formats, i.e. `.npy`/`.npz`, are portable. In principle, they should be, for as long as NumPy itself is available on the platform (the size of floats and integers, their endianness, the shape, and other metadata should all be saved in the file itself).
Most likely, we want some benchmarks for this, to continuously ensure that we are able to load these arrays.

**Comment by scarrazza** [comment]
Following #1015, we have to implement the possibility to store the full circuit and provide a method for loading.
