### ISSUE TITLE
Fix docs workflow to run with Poetry

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibo#818]
> Btw, is sphinx-build missing [qiboteam/qibo/actions/runs/4342411482/jobs/7583613358](https://github.com/qiboteam/qibo/actions/runs/4342411482/jobs/7583613358)?

Different problem: `sphinx-build` should be part of the `Sphinx` package, that is present
https://github.com/qiboteam/qibo/blob/341f502fec4c30644f3a23180cf30173b59c8174/pyproject.toml#L37-L38
but in a separate group of dev dependencies.

We should specify them in the workflow extras, as done in the other two workflows:
https://github.com/qiboteam/qibo/blob/341f502fec4c30644f3a23180cf30173b59c8174/.github/workflows/rules.yml#L23

_Originally posted by @AleCandido in https://github.com/qiboteam/qibo/issues/814#issuecomment-1455927392_

This has a firs part to be performed in the `workflows` repo, since the docs building workflow has the `inputs.poetry-extras` key inside https://github.com/qiboteam/workflows/blob/0aac7f146611b4e4bf05a35758658af60ff86a80/.github/workflows/build-docs.yml#L50, but not exposed.

It should be propagated to the workflow in this repo, and passing `--with docs`, similar to what is done in the tests one.

**Comment by scarrazza** [comment]
Is someone looking into this?

**Comment by scarrazza** [comment]
I am asking this because I would like to release 0.1.12 soon, and I believe that this bug will block the documentation generation.

**Comment by Edoardo-Pedicillo** [comment]
Yes, I am working on it.
