### ISSUE TITLE
The adiabatic evolution model alters the h0 object when using symbolic hamiltonians

### ISSUE THREAD

**Issue by igres26** [qiboteam/qibo#824]
It seems like the `AdiabaticEvolution` model replaces things on the initial Hamiltonian, making repeated adiabatic evolutions without re-defining this initial Hamiltonian fail. 

This should reproduce the issue:

```python

import numpy as np
from qibo import hamiltonians
from qibo.models.evolution import AdiabaticEvolution

nqubits = 5

h_x = hamiltonians.X(nqubits, dense=False)
print(h_x.ground_state())

h_ising = hamiltonians.TFIM(nqubits, h=1.0, dense=False)
print(h_ising.ground_state())

s = lambda t: t
evolve = AdiabaticEvolution(h_x, h_ising, s, dt=0.01, solver='exp')
final_state = evolve(final_time=10)
print(final_state)

print(h_x.ground_state()) #<--- This is now changed!
print(h_ising.ground_state())

evolve = AdiabaticEvolution(h_x, h_ising, s, dt=0.01, solver='exp')
final_state = evolve(final_time=10)
print(final_state) #<--- This has now changed too then!

```

You will notice how the h_x has changed.

This is not the case with `dense=True` Hamiltonians.

Why does this happen? Should this be fixed, or just properly documented?

**Comment by scarrazza** [comment]
Shall we close this issue?

**Comment by MatteoRobbiati** [comment]
> Shall we close this issue?

I think this is expected if using `qibojit` backend and it doesn't occur in case of `numpy` backend. @stavros11 and @andrea-pasquale what you think about this?
