### ISSUE TITLE
Quantum annealing with a sixth order Hamiltonian

### ISSUE THREAD

**Issue by lucaanutricati** [qiboteam/qibo#839]
I'm doing simulated quantum annealing with qibo and I have an issue with an Hamiltonian with 6 coupled qubits (I don't have any issue if the Hamiltonian is at most quintic). Here is a very simple code 

```from qibo import hamiltonians
from qibo import models
from qibo.symbols import X, Z
import numpy as np


time_steps = 2    # number of time-steps 
time_final = 20
delta_t= time_final/time_steps 
dt = 0.01

N= 6 #number of qubits

 #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #
 
if __name__ == '__main__':
  
  SH1 = Z(0)*Z(1)*Z(2)*Z(3)*Z(4)*Z(5) #### Sextic Hamiltonian

  # Initial Hamiltonian
  SH0 = sum( 2* (0.5-0.5*X(i)) for i in range(N))
  
  # Define a Hamiltonian using the above form
  H0 = hamiltonians.SymbolicHamiltonian(SH0)
  H1 = hamiltonians.SymbolicHamiltonian(SH1)

  #Anneal schedule
  def s(t):
      return 0.5 + 0.5 * ((t - 0.5)/0.5)**3
  
  #Now the evolution
  evolve = models.AdiabaticEvolution(H0, H1, s, dt=dt)

  #definition of the initial states
  initial_state = np.ones(2**N) / np.sqrt(2**N)
 
  def out_state(t,in_state):
      return evolve(final_time=t, initial_state=in_state)

  in_state = initial_state
    
  for k in range(time_steps):
    time_k = (k+1)* delta_t
    fs = out_state(time_k, initial_state )  
```

The error I get is 

```
TypeError: No matching definition for argument type(s) array(complex128, 1d, C), array(complex128, 2d, F), array(int32, 1d, C), int64, array(int64, 1d, C)
```

when it calls the ``evolve`` function which in turn is defined through ``models.AdiabaticEvolution``.

Everything goes fine if I change the Hamiltonian to a quintic one. Is this related to QIBO?

**Comment by MatteoRobbiati** [comment]
Thank you for opening this. 
I tried this code and it worked. 

Anyway, this problem seems to me related to a mismatch of dimension of size in variables types, probably related to `numba` in `qibojit` (it should work on `numpy` backend). 
@andrea-pasquale maybe you can better understand this.

**Comment by andrea-pasquale** [comment]
Thank you for the issue.
As @MatteoRobbiati was saying the problem seems to be related to the [`NumbaBackend`](https://github.com/qiboteam/qibojit/blob/decc9e739e2ec294530b33e258d2aee6c6bcb962/src/qibojit/backends/cpu.py#L25) in qibojit.
Also in my case I was able to run the code without any errors. Although the numba backend was quite slow so probably there is something wrong.
Which versions of qibojit, qibo and numba are you using @lucaanutricati?

**Comment by lucaanutricati** [comment]
Many thanks for the help.
Versions:  numba is 0.54.1; qibo 0.1.11; qibojit 0.0.8

Anyway, it worked after updating qibo to 0.1.12.
