### ISSUE TITLE
Combining `expectation_from_samples` with measurements in the Pauli X/Y basis

### ISSUE THREAD

**Issue by chmwzc** [qiboteam/qibo#852]
I've been trying to use the `expectation_from_samples` method under `SymbolicHamiltonian` together with measurements in the Pauli X/Y basis (#799).
However, `expectation_from_samples` currently only accepts Hamiltonians with only Z's ([link](https://github.com/qiboteam/qibo/blob/master/src/qibo/hamiltonians/hamiltonians.py#L564)) and raises an error otherwise.
Is this check still necessary, and can it be removed?

Sample code:
```
from qibo import models, gates

from qibo.symbols import X, Y
from qibo.hamiltonians import SymbolicHamiltonian

# Hamiltonian term
ham_term = X(0)*Y(1)
sym_ham = SymbolicHamiltonian(ham_term)

# Get the basis rotation gates and target qubits from the Hamiltonian term
qubits = [factor.target_qubit for factor in sym_ham.terms[0].factors]
basis = [type(factor.gate) for factor in sym_ham.terms[0].factors]

# Run the circuit to get the output frequencies
circuit = models.Circuit(2)
circuit.add(gates.M(*qubits, basis=basis))
result = circuit(nshots=100)
freq = result.frequencies(binary=True)

# Only works for Z terms, raises an error if ham_term has X/Y terms
sym_ham.expectation_from_samples(freq, qubit_map=qubits) 
```
***

Other than that, a minor documentation [issue](https://qibo.science/qibo/stable/api-reference/qibo.html#qibo.hamiltonians.abstract.AbstractHamiltonian.expectation_from_samples) with `expectation_from_samples`: the lines under [freq](https://github.com/qiboteam/qibo/blob/4ca9ba961b4e7121d3e2d647a2030c61059d67ca/src/qibo/hamiltonians/abstract.py#L91) are missing 4 spaces😀

**Comment by scarrazza** [comment]
@AlejandroSopena are you looking into this and #719?

**Comment by AlejandroSopena** [comment]
I haven't looked at it in detail, but I can take care of it
