### ISSUE TITLE
Over 10k `tensorflow` warnings while testing documentation examples on Github

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#897]
As I showed @stavros11 in person, there is one or more documentation examples that lead to over 10 thousand warnings due to `tensorflow` trying to cast `complex128` to `float64`. Due to the amount of warnings, this is probably happening inside an optimization, but there is no reference to which example(s) raise the warnings. I could not reproduce the warnings locally.

**Comment by MatteoRobbiati** [comment]
I managed to reproduce the warnings by running the following:

```python
import numpy as np

from qibo.models import Circuit
from qibo import gates, symbols, hamiltonians, set_backend
import tensorflow as tf

set_backend('tensorflow')

x = tf.Variable(np.random.randn(2))

with tf.GradientTape() as tape:

    c = Circuit(1)
    c.add(gates.RX(q=0, theta=x[0]))
    c.add(gates.RY(q=0, theta=x[1]))
    c.add(gates.M(0))

    form = symbols.Z(0)
    ham = hamiltonians.SymbolicHamiltonian(form)

    exp = ham.expectation(c.execute().state())

gradients = tape.gradient(exp, [x])[0].numpy()
```

As you said, this can be fixed by setting `dtype=tf.complex128` into the `tf.Variable` definition.
We need to catch where `tf.GradientTape` is used.
