### ISSUE TITLE
Errors without density matrices

### ISSUE THREAD

**Issue by igres26** [qiboteam/qibo#91]
As discussed in the previous meeting, an error simulation that does not require more memory is a good alternative in order to test noise effects on larger quantum circuits.

This approach is not fast, as one will have to compute the noisy circuit every time a measurement is made, but might be the only alternative in cases where there is not enough memory to store the density matrices.

**Comment by scarrazza** [comment]
@stavros11 what is the status of this?

**Comment by stavros11** [comment]
As of #276 this should be implemented for most noise channels. Noise is simulated without density matrices by executing state vector simulation multiple times with random choices for the noise gates.
