### ISSUE TITLE
Partial trace calculation

### ISSUE THREAD

**Issue by Juanfurk** [qiboteam/qibo#929]
Hii!! Sorry to bother, but I have been looking at backends/abstract for the partial trace function and I have seen it is not implemented yet. However, when computing the entanglement entropy from callbacks I saw that it uses the partial trace function, which as I said it does not seem implemented yet. I would like to ask if you know how the entanglement entropy is computed then and if there is an explicit way on qibo to estimate the partial trace. It would be very useful for my Master Thesis and for qibo, as we will try to implement some of our work in the qibo repository.

**Comment by renatomello** [comment]
https://github.com/qiboteam/qibo/blob/master/src/qibo/backends/numpy.py#L641
