### ISSUE TITLE
maxcut class

### ISSUE THREAD

**Issue by shangtai** [qiboteam/qibo#933]
I came across the maxcut class in Qibo and came across the following code:

```
def MaxCut(nqubits, dense=True, backend=None):
    """Max Cut Hamiltonian.

    .. math::
        H = - \\sum _{i,j=0}^N  \\frac{1 - Z_i Z_j}{2}.

    Args:
        nqubits (int): number of quantum bits.
        dense (bool): If ``True`` it creates the Hamiltonian as a
            :class:`qibo.core.hamiltonians.Hamiltonian`, otherwise it creates
            a :class:`qibo.core.hamiltonians.SymbolicHamiltonian`.
    """
    import sympy as sp
    from numpy import ones

    Z = sp.symbols(f"Z:{nqubits}")
    V = sp.symbols(f"V:{nqubits**2}")
    sham = -sum(
        V[i * nqubits + j] * (1 - Z[i] * Z[j])
        for i in range(nqubits)
        for j in range(nqubits)
    )
    sham /= 2

    v = ones(nqubits**2)
    smap = {s: (i, matrices.Z) for i, s in enumerate(Z)}
    smap.update({s: (i, v[i]) for i, s in enumerate(V)})

    ham = SymbolicHamiltonian(sham, smap, backend=backend)
    if dense:
        return ham.dense
    return ham
```

Maxcut is an optimization problem where the question of interest is what is the maximum cut that we can find in a particular graph. However, the input argument just takes in the problem size,  it is independent of the graph.  The hamiltonian constructed just returns the  corresponding Maxcut Hamiltonian for the clique corresponding to the size. I wonder if this is intentionally coded for an application.

**Comment by scarrazza** [comment]
@shangtai please have a look at these definitions: https://github.com/scarrazza/QITE/blob/main/hamiltonians.py

**Comment by shangtai** [comment]
@scarrazza Hi Stefano, thanks for the reference.

I pass the following based code to my team for benchmarking previously.  Here w is the matrix representing the weight.


```
import sympy as sp
Z = sp.symbols(f"Z:{n}")
sham = -sum(
    w[i,j] * (1 - Z[i] * Z[j])
    for i in range(n)
    for j in range(i+1, n)
)
sham /= 2

smap = {s: (i, matrices.Z) for i, s in enumerate(Z)}
ham = SymbolicHamiltonian(sham, smap)
```
