### ISSUE TITLE
Adiabatic evolution class state callback returns double the expected states

### ISSUE THREAD

**Issue by jose-miralles** [qiboteam/qibo#973]
When adding state callbacks to the adiabatic evolution function the resulting state object has repeated states for each state.

To reproduce one can follow the code depicted in the images which also shows the issue.

![Screenshot 2023-07-19 at 10 35 22](https://github.com/qiboteam/qibo/assets/139958400/75d2bdec-a402-4414-b7d5-c77cad580a37)
![Screenshot 2023-07-19 at 10 37 07](https://github.com/qiboteam/qibo/assets/139958400/6a81ff49-3394-4465-9f57-0fd41f0f71e0)

Im using the latest qibo package (v 0.1.14) . I would expect both lengths to match or in this case to differ by 1 if counting the initial state when t=0 which it does.

**Comment by MatteoRobbiati** [comment]
It seems to me the `state` object is casted twice, once [when the evolutionary step is executed](https://github.com/qiboteam/qibo/blob/4055c888d28f1eb2ba76ab60b3fefe39573cb86e/src/qibo/models/evolution.py#L92) and once [when we call the `apply`](https://github.com/qiboteam/qibo/blob/4055c888d28f1eb2ba76ab60b3fefe39573cb86e/src/qibo/callbacks.py#L161) method if `State` is a callback. In fact, by removing [this line](https://github.com/qiboteam/qibo/blob/4055c888d28f1eb2ba76ab60b3fefe39573cb86e/src/qibo/callbacks.py#L161) the final results list is correct.

I am wondering if the `apply` method is necessary for the `State(Callback)` class. What do you think about it @stavros11?

**Comment by stavros11** [comment]
Thanks for checking @MatteoRobbiati. I think you are right, we should do the `append` in one place only. 

I think the motivation of having it inside the `apply` method was that it will also work when the callback is used on its own, not as part of an evolution. Also I think it is used when the callback is used as part of circuits, where there is no second `append` done by the circuit. So maybe it makes more sense to remove the `append` from the evolution instead?

It would also be good to follow the same approach for all callbacks. For example now the entanglement entropy seems to be similar (it has `append` in `apply`), while the other callbacks don’t, so I am assuming they won’t work with circuits.
