### ISSUE TITLE
MVC 2.0

### ISSUE THREAD

**Issue by shangtai** [qiboteam/qibo#993]
I was trying to fix the MVC branch previously and I have created MVC 2.0 branch to do so.

Unfortunately, build (macos-latest, 3.9) fails though the Windows and Ubuntu versions work. Can you advise me on what are the potential things that I should look out for?

<img width="296" alt="Screenshot 2023-08-12 at 3 27 16 AM" src="https://github.com/qiboteam/qibo/assets/10039046/f37b2a76-c17f-4752-8e05-cf9d1b034e54">

**Comment by scarrazza** [comment]
@shangtai I have restarted the failed job, please have a look: https://github.com/qiboteam/qibo/actions/workflows/deploy.yml?query=branch%3Amvc2.0

**Comment by shangtai** [comment]
Thanks @scarrazza  I did the same thing for QAP as well, should I open a pull request for the branches to be merged?

**Comment by scarrazza** [comment]
Yes please.

**Comment by scarrazza** [comment]
Completed.
